#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![doc = "Moso's migration system: entities in, a reviewable migration out, applied safely."]
//!
//! # The model
//!
//! **Rust entities are the source of truth.** A committed snapshot,
//! `migrations/.schema.json`, records the schema as of the last generated
//! migration. `moso db make-migration` diffs the entities against the snapshot
//! and writes a migration you read before applying.
//!
//! ```text
//!    src/models/*.rs  (#[derive(Entity)])
//!             │  EntityDescriptor  (generated by the derive)
//!             ▼
//!    ┌─────────────────┐   diff    ┌────────────────────────────┐
//!    │ desired schema  │──────────▶│ migrations/00042_add_x.sql │
//!    └─────────────────┘           └────────────────────────────┘
//!             ▲                                  │ apply
//!    ┌─────────────────┐                         ▼
//!    │ migrations/     │◀──────── update ──── database
//!    │  .schema.json   │                    (moso_migrations table)
//!    └─────────────────┘
//! ```
//!
//! This is Django's model, not Rails': the diff is automatic, the file is
//! reviewable, and the snapshot means Moso never has to introspect a live
//! database to know what it *intended*. It also means the generator works
//! offline and produces the same file on every machine — which is what makes
//! the idempotence guarantee below possible at all.
//!
//! ```no_run
//! use moso_migrate::generator::Generator;
//! use moso_migrate::rename::Prompt;
//! use moso_migrate::runner::{Runner, RunnerOptions};
//! use moso_orm::Backend;
//!
//! # async fn example(entities: &[&moso_orm::descriptor::EntityDescriptor]) -> moso_migrate::Result<()> {
//! // moso db make-migration
//! let generator = Generator::new("migrations", Backend::Postgres);
//! if let Some(generated) = generator.make_migration(entities, None, &Prompt::stdio())? {
//!     generated.write()?;
//!     println!("wrote {}", generated.path().display());
//! }
//!
//! // moso db migrate
//! let mut runner = Runner::open("migrations", "postgres://moso:moso@localhost/app").await?;
//! let report = runner.migrate(&RunnerOptions::default()).await?;
//! println!("{} applied", report.applied().len());
//! runner.close().await;
//! # Ok(())
//! # }
//! ```
//!
//! # The three guarantees
//!
//! **Round trip.** A fresh database with every migration applied, read back,
//! equals the schema the migrations were generated from. Proved on both
//! backends in `tests/mandatory.rs`.
//!
//! **Reversibility.** Apply, roll back, apply again: the schema is the same
//! each time.
//!
//! **Idempotence.** `make-migration` twice in a row produces exactly one
//! migration. A generator that emits spurious diffs is unusable, and this is
//! the test that catches it the moment it starts.
//!
//! # The safety policy
//!
//! Migrations run in production, so:
//!
//! 1. **Never auto-apply in production.** [`runner::RunnerOptions::profile`].
//! 2. **Destructive operations are emitted commented out** and refuse to run
//!    until a human uncomments them or passes `--allow-destructive`
//!    ([`file::MigrationFile::statements_to_apply`]).
//! 3. **Advisory-lock guarded**, so twenty pods starting at once apply each
//!    migration exactly once ([`ledger::MigrationLock`]).
//! 4. **Transactional** unless the file says otherwise; a failed
//!    non-transactional migration is marked **dirty** and `moso db status`
//!    explains exactly what to do ([`runner::Runner::apply_one`]).
//! 5. **Checksums.** Editing an applied migration is detected and refused
//!    ([`Checksum`]).
//! 6. **`lock_timeout` and `statement_timeout`** on every migration
//!    ([`runner::Runner::set_timeouts`]). This one default prevents a shocking
//!    number of outages.
//! 7. **Expand/contract guidance** for changes that break a rolling deploy
//!    ([`advice::Advice`]).
//!
//! # The map
//!
//! | Module | Contents |
//! | --- | --- |
//! | [`schema`] | the snapshot: [`Schema`], [`Table`](schema::Table), [`Column`](schema::Column), and `Schema::from_entities` |
//! | [`diff`] | [`Diff`] and [`Change`] — what differs, with no SQL in sight |
//! | [`rename`] | the ⚠ rows of the operation table: [`Oracle`](rename::Oracle), [`Prompt`](rename::Prompt), [`Scripted`](rename::Scripted) |
//! | [`plan`] | [`Plan`] — the zero-downtime idioms and the SQLite table rebuild |
//! | [`emit`] | DDL to reviewable SQL text, literals inlined |
//! | [`mod@file`] | the migration file format and the SQL statement splitter |
//! | [`generator`] | `moso db make-migration`, end to end |
//! | [`runner`] | `moso db migrate`, `rollback`, `status`, `redo` |
//! | [`ledger`] | the `moso_migrations` table and the migration lock |
//! | [`introspect`] | a live database back into a [`Schema`] |
//! | [`check`] | `moso db check` — drift in both directions |
//! | [`squash`] | `moso db squash` |
//! | [`seed`] | `moso db seed` |
//! | [`command`] | one call and one JSON report per `moso db` subcommand |
//! | [`rust_migration`] | migrations that need application logic |
//! | [`advice`] | expand/contract plans |
//! | [`conn`] | the single connection a run holds, and why it is not a pool |
//!
//! [`command`] is the layer an application's `src/db.rs` calls: it answers each
//! `--db-*` flag with one `Serialize` report, so the CLI can render a table
//! without linking this crate. Everything it composes stays public underneath
//! it, for the cases its stable signature does not cover.
//!
//! # What this crate does *not* do
//!
//! It does not read your entity graph for you.
//! [`Schema::from_entities`] takes `&[&EntityDescriptor]`, and collecting those
//! is the application's job — `moso db make-migration` links against the
//! application binary to do it. There is no link-time registry (ADR-0004), so
//! there cannot be a magic global list of entities, and this crate does not
//! pretend there is one.

pub mod advice;
pub mod check;
pub mod command;
pub mod conn;
pub mod diff;
pub mod emit;
pub mod error;
pub mod file;
pub mod generator;
pub mod hash;
pub mod introspect;
pub mod ledger;
pub mod plan;
pub mod rename;
pub mod runner;
pub mod rust_migration;
pub mod schema;
pub mod seed;
pub mod squash;
pub mod version;

pub use crate::check::Drift;
pub use crate::diff::{Change, Diff};
pub use crate::error::{Error, Result};
pub use crate::generator::{Generated, Generator};
pub use crate::hash::Checksum;
pub use crate::plan::{Operation, Plan};
pub use crate::runner::{MigrateReport, Runner, RunnerOptions, Status};
pub use crate::schema::Schema;
pub use crate::version::{MigrationId, Version};

/// Everything a migration or a composition root normally needs, in one `use`.
///
/// ```
/// use moso_migrate::prelude::*;
///
/// let schema = Schema::empty();
/// assert!(schema.is_empty());
/// ```
pub mod prelude {
    pub use crate::advice::Advice;
    pub use crate::check::{Drift, check, compare};
    pub use crate::diff::{Change, Diff};
    pub use crate::error::{Error, Result};
    pub use crate::generator::{Generated, Generator};
    pub use crate::plan::{Operation, Plan};
    pub use crate::rename::{DropAndAdd, Oracle, Prompt, RefuseToGuess, Scripted};
    pub use crate::runner::{MigrateReport, Runner, RunnerOptions, Status};
    pub use crate::rust_migration::{Migrator, RustMigration};
    pub use crate::schema::Schema;
    pub use crate::seed::{Seed, SeedOptions, Seeds};
    pub use crate::version::{MigrationId, Version};
    pub use futures_util::future::BoxFuture;
}
