//! Turning an OpenAPI document into a typed client.
//!
//! # Shape
//!
//! ```text
//! document ──▶ model::Api ──▶ typescript::emit ──▶ [types.ts, client.ts, index.ts]
//!                        └──▶ rust::emit       ──▶ [mod.rs, models.rs, client.rs]
//! ```
//!
//! [`model`] does every hard reading: `$ref` resolution, `allOf`/`oneOf`
//! normalisation, pulling `null` out of a type union, hoisting an anonymous
//! object into a name. The emitters do no interpretation at all — they render a
//! model that has already decided what everything is. That split is why the two
//! targets cannot disagree about a document, and why the interesting cases are
//! tested once rather than by grepping generated text twice.
//!
//! # Determinism is a feature, not a nicety
//!
//! A generated client is meant to be committed, reviewed and diffed, and
//! `moso client --check` is meant to fail a build when it drifts from the
//! contract. Both of those only work if one document always produces the same
//! bytes: no clock, no host name, no absolute path, no output directory, no CLI
//! version, and every map sorted before it is read. The one thing that varies
//! with the *invocation* is which files are written, and that is chosen by
//! `--lang`.
//!
//! # What a target may not do
//!
//! Silently drop something. A construct with no faithful representation becomes
//! an opaque type carrying the sentence that explains it, right where a reader
//! will meet it; a construct only partly represented adds a line to the
//! generated file's header and to what the command prints. A client that is
//! quietly wrong is worse than one that admits a gap, because nobody goes
//! looking for it.

pub mod model;
pub mod rust;
pub mod typescript;

use crate::client::model::Api;

/// One file a generator wants written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Emitted {
    /// Where it goes, relative to `--out`.
    pub path: String,
    /// Its whole contents, trailing newline included.
    pub contents: String,
}

/// A language a client can be generated for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// Dependency-free TypeScript over `fetch`.
    TypeScript,
    /// Transport-agnostic Rust over `serde`.
    Rust,
}

impl Target {
    /// The value `--lang` takes.
    #[must_use]
    pub const fn flag(self) -> &'static str {
        match self {
            Target::TypeScript => "ts",
            Target::Rust => "rust",
        }
    }

    /// How the language is spelled in prose.
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Target::TypeScript => "TypeScript",
            Target::Rust => "Rust",
        }
    }
}

/// Generate every file of one client.
///
/// The returned list is sorted by path, so a caller can write it, diff it or
/// print it without imposing an order of its own.
#[must_use]
pub fn generate(api: &Api, target: Target) -> Vec<Emitted> {
    let mut files = match target {
        Target::TypeScript => typescript::emit(api),
        Target::Rust => rust::emit(api),
    };
    files.sort_by(|left, right| left.path.cmp(&right.path));
    files
}

/// The lines every generated file opens with, without comment markers.
///
/// `notes` is passed only for the file a reader lands in first, so that a
/// caveat about the document appears once rather than three times.
#[must_use]
pub fn header_lines(api: &Api, lang: &str, what: &str, notes: &[String]) -> Vec<String> {
    let mut lines = vec![
        format!("Code generated by `moso client --lang {lang}`. DO NOT EDIT."),
        String::new(),
        format!("{} {} — {what}.", api.title, api.version),
        String::new(),
        format!("Regenerate:   moso client --lang {lang} --out DIR"),
        format!("Check in CI:  moso client --lang {lang} --out DIR --check"),
    ];

    if !notes.is_empty() {
        lines.push(String::new());
        lines.push("Things this document says that the generated client cannot:".to_owned());
        for note in notes {
            for (index, line) in wrap(note, 84).into_iter().enumerate() {
                lines.push(if index == 0 {
                    format!("  - {line}")
                } else {
                    format!("    {line}")
                });
            }
        }
    }

    lines
}

/// Break prose into lines of at most `width` columns.
///
/// Hard newlines in the input are kept, because a description that was written
/// as paragraphs should stay paragraphs. A word longer than `width` is left
/// long rather than broken: a URL or a type name is worse split than wide. A
/// line's own leading spaces are kept on every line it becomes, and a line
/// opening a `- ` bullet gets a two-space hanging indent, so a wrapped list
/// item still reads as one item.
///
/// Re-wrapping already-wrapped text is a no-op, which matters because a doc
/// comment is assembled from lines that have each already been through here.
#[must_use]
pub fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    for paragraph in text.replace('\r', "").split('\n') {
        let indent: String = paragraph
            .chars()
            .take_while(|space| *space == ' ')
            .collect();
        let hanging = if paragraph.trim_start().starts_with("- ") {
            format!("{indent}  ")
        } else {
            indent.clone()
        };

        let mut current = String::new();
        let mut prefix = indent.clone();
        for word in paragraph.split_whitespace() {
            if current.is_empty() {
                current.push_str(&prefix);
                current.push_str(word);
            } else if current.chars().count() + 1 + word.chars().count() <= width {
                current.push(' ');
                current.push_str(word);
            } else {
                lines.push(std::mem::take(&mut current));
                prefix.clone_from(&hanging);
                current.push_str(&prefix);
                current.push_str(word);
            }
        }
        lines.push(current);
    }
    lines
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn api() -> Api {
        Api::parse(&json!({
            "openapi": "3.1.1",
            "info": {"title": "Shop", "version": "2.0.0"},
            "paths": {},
        }))
        .expect("parses")
    }

    #[test]
    fn wrapping_keeps_paragraphs_and_never_breaks_a_word() {
        assert_eq!(wrap("one two three", 7), vec!["one two", "three"]);
        assert_eq!(wrap("a\n\nb", 20), vec!["a", "", "b"]);
        assert_eq!(
            wrap("supercalifragilistic", 5),
            vec!["supercalifragilistic"]
        );
        assert_eq!(wrap("", 10), vec![""]);
    }

    #[test]
    fn a_wrapped_bullet_stays_one_bullet() {
        let wrapped = wrap("- 500 the server broke", 10);
        assert_eq!(wrapped, vec!["- 500 the", "  server", "  broke"]);
        // Feeding the result back through must not move it again: a doc comment
        // is assembled from lines that have already been wrapped once.
        let again: Vec<String> = wrapped.iter().flat_map(|line| wrap(line, 10)).collect();
        assert_eq!(again, wrapped);
    }

    #[test]
    fn the_header_never_names_anything_that_varies_between_machines() {
        let lines = header_lines(&api(), "ts", "the client itself", &[]).join("\n");
        assert!(lines.contains("Shop 2.0.0"), "{lines}");
        assert!(lines.contains("DO NOT EDIT"), "{lines}");
        assert!(!lines.contains('/'), "no path may appear: {lines}");
    }

    #[test]
    fn a_note_is_repeated_into_the_header_so_a_reader_meets_it() {
        let lines = header_lines(
            &api(),
            "rust",
            "the models",
            &["`not` is ignored".to_owned()],
        );
        assert!(lines.iter().any(|line| line.contains("- `not` is ignored")));
    }

    #[test]
    fn every_target_produces_files_in_a_stable_order() {
        for target in [Target::TypeScript, Target::Rust] {
            let files = generate(&api(), target);
            let mut sorted: Vec<&str> = files.iter().map(|file| file.path.as_str()).collect();
            let original = sorted.clone();
            sorted.sort_unstable();
            assert_eq!(original, sorted, "{} is unsorted", target.label());
            assert!(!files.is_empty());
        }
    }

    #[test]
    fn the_two_targets_are_told_apart_by_their_flag() {
        assert_eq!(Target::TypeScript.flag(), "ts");
        assert_eq!(Target::Rust.flag(), "rust");
        assert_eq!(Target::Rust.label(), "Rust");
    }
}
