//! `@@PATH@@` — the @@MODULE@@ resource.
//!
//! Generated by `moso generate endpoint @@MODULE@@`. Everything here is
//! ordinary code: edit it, delete what you do not need, move the types
//! somewhere else. The generator's job was the first draft, not the design.
//!
//! The store is an in-memory `Mutex<Vec<_>>` so that the module compiles and
//! its tests pass the moment it is generated. Replace it with your database.

use std::sync::{Arc, Mutex};

use moso::prelude::*;

// ---------------------------------------------------------------------------
// payloads
// ---------------------------------------------------------------------------

/// What `POST @@PATH@@` accepts.
///
/// Each `#[schema(..)]` attribute produces two things that cannot drift apart:
/// the runtime check behind the `422`, and the constraint published in the
/// OpenAPI document.
#[derive(Schema, Debug, Clone)]
pub struct Create@@TYPE@@ {
    /// A short human-readable label.
    #[schema(len = 1..=200, trim)]
    pub name: String,
}

/// What `PATCH @@PATH@@/{id}` accepts.
///
/// Every field is optional, because absent means "leave it alone" — which is
/// what `PATCH` means. A `len` on an `Option` checks the value only when one is
/// present, so "absent" and "invalid" stay distinguishable.
#[derive(Schema, Debug, Clone, Default)]
pub struct Update@@TYPE@@ {
    /// A replacement label.
    #[schema(len = 1..=200, trim)]
    pub name: Option<String>,
}

/// What every @@SINGULAR@@ endpoint returns.
#[derive(Schema, Debug, Clone)]
pub struct @@TYPE@@ {
    /// Server-assigned identifier.
    pub id: u64,
    /// The label this @@SINGULAR@@ was created with.
    pub name: String,
}

// ---------------------------------------------------------------------------
// storage
// ---------------------------------------------------------------------------

/// Where @@TYPE_PLURAL@@ live until you give them a database.
///
/// Registered once at boot with `.provide(@@TYPE@@Store::default())` and reached
/// by a handler through `Inject<@@TYPE@@Store>`. Forgetting the `provide` is a
/// boot error naming this type, not a panic on the first request.
#[derive(Debug, Clone, Default)]
pub struct @@TYPE@@Store {
    /// Every @@SINGULAR@@, and the identifier the next one will get.
    rows: Arc<Mutex<(u64, Vec<@@TYPE@@>)>>,
}

impl @@TYPE@@Store {
    /// Every @@SINGULAR@@, oldest first.
    #[must_use]
    pub fn list(&self) -> Vec<@@TYPE@@> {
        self.rows.lock().map(|rows| rows.1.clone()).unwrap_or_default()
    }

    /// Fetch one by identifier.
    #[must_use]
    pub fn get(&self, id: u64) -> Option<@@TYPE@@> {
        let rows = self.rows.lock().ok()?;
        rows.1.iter().find(|row| row.id == id).cloned()
    }

    /// Store a new @@SINGULAR@@ and return it with its identifier.
    #[must_use]
    pub fn create(&self, body: Create@@TYPE@@) -> @@TYPE@@ {
        let mut rows = self.rows.lock().unwrap_or_else(|error| error.into_inner());
        rows.0 += 1;
        let created = @@TYPE@@ {
            id: rows.0,
            name: body.name,
        };
        rows.1.push(created.clone());
        created
    }

    /// Apply a patch, returning the updated @@SINGULAR@@.
    #[must_use]
    pub fn update(&self, id: u64, body: Update@@TYPE@@) -> Option<@@TYPE@@> {
        let mut rows = self.rows.lock().unwrap_or_else(|error| error.into_inner());
        let row = rows.1.iter_mut().find(|row| row.id == id)?;
        if let Some(name) = body.name {
            row.name = name;
        }
        Some(row.clone())
    }

    /// Remove one, reporting whether it was there.
    #[must_use]
    pub fn delete(&self, id: u64) -> bool {
        let mut rows = self.rows.lock().unwrap_or_else(|error| error.into_inner());
        let before = rows.1.len();
        rows.1.retain(|row| row.id != id);
        before != rows.1.len()
    }
}

// ---------------------------------------------------------------------------
// handlers
// ---------------------------------------------------------------------------

/// List every @@SINGULAR@@.
///
/// The first line of this doc comment becomes the operation's `summary` in the
/// OpenAPI document and the rest becomes its `description`.
#[endpoint]
async fn list(Inject(store): Inject<@@TYPE@@Store>) -> Result<Json<Vec<@@TYPE@@>>> {
    Ok(Json(store.list()))
}

/// Fetch one @@SINGULAR@@ by identifier.
#[endpoint]
async fn show(
    Inject(store): Inject<@@TYPE@@Store>,
    Path(id): Path<u64>,
) -> Result<Json<@@TYPE@@>> {
    store
        .get(id)
        .map(Json)
        .ok_or_else(|| Error::not_found(format!("no @@SINGULAR@@ with id {id}")))
}

/// Create a @@SINGULAR@@.
///
/// `Json<Create@@TYPE@@>` cannot exist unless the body parsed *and* validated,
/// so this function never checks its own input.
#[endpoint]
async fn create(
    Inject(store): Inject<@@TYPE@@Store>,
    Json(body): Json<Create@@TYPE@@>,
) -> Result<Created<@@TYPE@@>> {
    let created = store.create(body);
    let location = format!("@@PATH@@/{}", created.id);
    Ok(Created::at(location, created))
}

/// Change some fields of a @@SINGULAR@@.
#[endpoint]
async fn update(
    Inject(store): Inject<@@TYPE@@Store>,
    Path(id): Path<u64>,
    Json(body): Json<Update@@TYPE@@>,
) -> Result<Json<@@TYPE@@>> {
    store
        .update(id, body)
        .map(Json)
        .ok_or_else(|| Error::not_found(format!("no @@SINGULAR@@ with id {id}")))
}

/// Delete a @@SINGULAR@@.
#[endpoint]
async fn destroy(
    Inject(store): Inject<@@TYPE@@Store>,
    Path(id): Path<u64>,
) -> Result<NoContent> {
    if store.delete(id) {
        Ok(NoContent)
    } else {
        Err(Error::not_found(format!("no @@SINGULAR@@ with id {id}")))
    }
}

/// Every route this resource serves.
pub fn router() -> Router {
    moso::routes! {
        GET    "@@PATH@@"      => list,
        POST   "@@PATH@@"      => create,
        GET    "@@PATH@@/{id}" => show,
        PATCH  "@@PATH@@/{id}" => update,
        DELETE "@@PATH@@/{id}" => destroy,
    }
    .tag("@@MODULE@@")
}
