//! The failures the @@MODULE@@ domain can produce.
//!
//! Generated by `moso generate error @@MODULE@@`.
//!
//! `#[derive(moso::Error)]` maps each variant onto an RFC 9457 problem
//! document: a status, a `type` URI, a title and an interpolated `detail`. The
//! generated `From<@@TYPE@@Error> for moso::Error` is what makes `?` work in a
//! handler, and the generated `Describe` is what puts these statuses in the
//! OpenAPI document when a handler declares `#[endpoint(errors = @@TYPE@@Error)]`.

/// Everything the @@MODULE@@ domain can refuse to do.
#[derive(Debug, moso::Error)]
#[error(type_base = "https://example.com/errors/")]
pub enum @@TYPE@@Error {
    /// No @@SINGULAR@@ has that identifier.
    #[error(status = 404, detail = "No @@SINGULAR@@ with id {id}")]
    NotFound {
        /// The identifier that was asked for.
        id: String,
    },

    /// Two @@TYPE_PLURAL@@ would end up with the same name.
    #[error(status = 409, detail = "The name `{name}` is already taken")]
    NameTaken {
        /// The name that collided.
        name: String,
    },

    /// A PATCH that asked for nothing.
    #[error(status = 422, detail = "Provide at least one field to change")]
    NothingToUpdate,

    /// The caller may not do this to somebody else's @@SINGULAR@@.
    #[error(status = 403, detail = "This @@SINGULAR@@ belongs to somebody else")]
    NotYours,
}

impl @@TYPE@@Error {
    /// The 404 for a @@SINGULAR@@ that is absent.
    #[must_use]
    pub fn not_found(id: impl std::fmt::Display) -> Self {
        Self::NotFound {
            id: id.to_string(),
        }
    }

    /// The 409 for a name that is already in use.
    #[must_use]
    pub fn name_taken(name: impl Into<String>) -> Self {
        Self::NameTaken { name: name.into() }
    }
}
