//! The `@@MODULE@@` middleware.
//!
//! Generated by `moso generate middleware @@MODULE@@`.
//!
//! `#[moso::middleware]` turns one `async fn` into a `tower::Layer` /
//! `tower::Service` pair — here `@@RAW_TYPE@@Layer` and `@@RAW_TYPE@@Service` —
//! named after the function and registered like any other layer:
//!
//! ```ignore
//! App::new(config).mount(routes::router().layer(@@RAW_TYPE@@Layer::new()))
//! ```
//!
//! Parameters before `req` are extracted before the function body runs, so an
//! `Inject<T>` works here and its provider requirement is folded into
//! `@@RAW_TYPE@@Layer::PROVIDER_REQ` — forgetting the matching `.provide(..)` is
//! a boot error naming the type, not a panic on the first request.

use moso::deps::http::HeaderValue;
use moso::middleware::Next;
use moso::prelude::*;
use moso::{Request, Response};

/// The header this middleware stamps onto every response.
pub const @@RAW_SCREAMING@@_HEADER: &str = "x-@@RAW_KEBAB@@";

/// Run on every request the router it is attached to serves.
///
/// The shape to copy: do the work that has to happen *before* the handler, call
/// `next.run(req)`, then do the work that has to happen after. Returning early
/// without calling `next` is how a guard rejects a request.
#[moso::middleware]
pub async fn @@RAW@@(req: Request, next: Next) -> Result<Response> {
    // Before the handler: inspect or modify the request.
    let started = std::time::Instant::now();

    // `next.run` yields the response itself, not a `Result`: a handler's own
    // failure has already been rendered into a problem document by the time it
    // reaches a middleware.
    let mut response = next.run(req).await;

    // After the handler: inspect or modify the response.
    let elapsed = started.elapsed();
    if let Ok(value) = HeaderValue::from_str(&format!("{}ms", elapsed.as_millis())) {
        response
            .headers_mut()
            .insert(@@RAW_SCREAMING@@_HEADER, value);
    }

    Ok(response)
}
