//! The `@@TYPE@@` payloads.
//!
//! Generated by `moso generate schema @@MODULE@@`.
//!
//! One type definition drives four things at once: deserialisation, validation,
//! the OpenAPI schema, and the JSON Pointer in the `422` a client gets when it
//! sends something wrong. There is no second place to keep in sync.

use moso::prelude::*;

/// What a client sends to create a @@SINGULAR@@.
#[derive(Schema, Debug, Clone)]
pub struct Create@@TYPE@@ {
    /// A short human-readable label.
    ///
    /// `len` is one attribute and it produces two things: the runtime check
    /// that rejects an empty name with `422` and `/name`, and the
    /// `minLength`/`maxLength` in the published schema. They cannot disagree.
    #[schema(len = 1..=200, trim)]
    pub name: String,

    /// Free-form tags.
    ///
    /// `each(..)` applies its constraints to every element, and a failure
    /// reports the index — `/tags/2` — rather than the whole field.
    #[schema(default, len = ..=10, each(len = 1..=32, pattern = r"^[a-z0-9-]+$"))]
    pub tags: Vec<String>,
}

/// What a client sends to change a @@SINGULAR@@.
///
/// Every field is optional: absent means "leave it alone", which is what
/// `PATCH` means.
#[derive(Schema, Debug, Clone, Default)]
pub struct Update@@TYPE@@ {
    /// A replacement label.
    #[schema(len = 1..=200, trim)]
    pub name: Option<String>,
}

/// What the API returns for one @@SINGULAR@@.
#[derive(Schema, Debug, Clone)]
pub struct @@TYPE@@ {
    /// Server-assigned identifier.
    pub id: u64,
    /// The label this @@SINGULAR@@ carries.
    pub name: String,
    /// The tags it was filed under.
    pub tags: Vec<String>,
}
