//! The @@MODULE@@ HTTP contract, exercised end to end.
//!
//! Generated by `moso generate test @@MODULE@@`.
//!
//! `App::into_service()` hands back the composed tower service — the real
//! router, the real middleware stack, the real dependency graph — so these
//! tests drive exactly what production serves without binding a port.

use moso::deps::axum::Router;
use moso::deps::axum::body::{Body, to_bytes};
use moso::deps::http::{Request, StatusCode};
use moso::deps::tower::ServiceExt;

/// Boot the application the way `main` does.
///
/// Every call builds a *fresh* application, and therefore a fresh store. A test
/// that writes and then reads has to send both requests through **one** service
/// — see [`a_@@SINGULAR@@_is_created_and_then_readable`] — or the read will look
/// at a different store than the write.
fn service() -> Router<()> {
    @@LIB_NAME@@::build()
        .expect("the application builds")
        .into_service()
}

/// Answer one request on `service`, leaving it usable for the next one.
async fn send_on(service: &Router<()>, request: Request<Body>) -> (StatusCode, String) {
    let response = service
        .clone()
        .oneshot(request)
        .await
        .expect("infallible");
    let status = response.status();
    let body = to_bytes(response.into_body(), 1 << 20).await.expect("body");
    (status, String::from_utf8_lossy(&body).into_owned())
}

/// Answer one request against a freshly built application.
async fn send(request: Request<Body>) -> (StatusCode, String) {
    send_on(&service(), request).await
}

fn get(path: &str) -> Request<Body> {
    Request::builder()
        .uri(path)
        .body(Body::empty())
        .expect("a valid request")
}

fn post_json(path: &str, body: &'static str) -> Request<Body> {
    Request::builder()
        .method("POST")
        .uri(path)
        .header("content-type", "application/json")
        .body(Body::from(body))
        .expect("a valid request")
}

#[tokio::test]
async fn @@MODULE@@_are_listed() {
    let (status, body) = send(get("@@PATH@@")).await;
    assert_eq!(status, StatusCode::OK, "{body}");
}

#[tokio::test]
async fn a_@@SINGULAR@@_is_created_and_then_readable() {
    // One service for both requests: the store lives in the application, so a
    // create and a read in two separately built applications never meet.
    let service = service();

    let (status, body) = send_on(&service, post_json("@@PATH@@", r#"{"name":"first"}"#)).await;
    assert_eq!(status, StatusCode::CREATED, "{body}");
    assert!(body.contains("first"), "{body}");

    let (status, body) = send_on(&service, get("@@PATH@@/1")).await;
    assert_eq!(status, StatusCode::OK, "{body}");
    assert!(body.contains("first"), "{body}");
}

#[tokio::test]
async fn an_invalid_body_is_rejected_with_a_pointer_to_the_field() {
    let (status, body) = send(post_json("@@PATH@@", r#"{"name":""}"#)).await;
    assert_eq!(status, StatusCode::UNPROCESSABLE_ENTITY, "{body}");
    // RFC 9457 problem+json, with an RFC 6901 pointer at the offending field.
    assert!(body.contains("/name"), "{body}");
}

#[tokio::test]
async fn a_@@SINGULAR@@_that_does_not_exist_is_a_404() {
    let (status, body) = send(get("@@PATH@@/999999")).await;
    assert_eq!(status, StatusCode::NOT_FOUND, "{body}");
}
