//! `#[job]` — an `async fn` becomes a background job.
//!
//! The macro leaves the user's function **exactly as written** and emits a
//! companion unit struct beside it (an expansion sketch, not a program):
//!
//! ```text
//! #[derive(Clone, Copy, Debug, Default)]
//! pub struct SendWelcomeEmail;
//!
//! impl ::moso::__private::Job for SendWelcomeEmail {
//!     type Args = SendWelcome;
//!     const NAME: &'static str = "send_welcome_email";
//!     const QUEUE: &'static str = "mail";
//!     const RETRIES: u32 = 5;
//!     const TIMEOUT: ::core::time::Duration = ::core::time::Duration::from_millis(120_000);
//!     const UNIQUE_FOR: Option<::core::time::Duration> = Some(…);
//!     const BACKOFF: ::moso::__private::Backoff = …;
//!
//!     async fn run(args: SendWelcome, ctx: ::moso::__private::JobCtx)
//!         -> ::moso::__private::JobResult
//!     {
//!         let db = ctx.inject::<Db>()?;             // one per `Inject(..)`
//!         send_welcome_email(args, ::moso::__private::Inject(db), ctx).await
//!     }
//! }
//! ```
//!
//! # Why a type and not a `fn` item
//!
//! Rust cannot attach an associated type or an associated const to a function,
//! and `Job` needs six of each. The same argument shapes `#[endpoint]`
//! (ADR-0013): the metadata has to live on a type, so the macro makes one.
//!
//! # The wire name is derived once and then pinned
//!
//! `NAME` is `send_welcome_email` — the function's own name, in snake case —
//! and **not** the Rust path. Renaming the module must not orphan 40,000 queued
//! rows, so when the function moves, `#[job(name = "…")]` keeps the old name.
//!
//! # What the parameters may be
//!
//! Exactly one payload (first), any number of `Inject(..)`, and an optional
//! `ctx: JobCtx`. That is the whole grammar, and every deviation is a compile
//! error with a `help:` line rather than a trait-resolution failure inside the
//! generated body.

use proc_macro2::{Span, TokenStream};
use quote::{ToTokens, format_ident, quote, quote_spanned};
use syn::parse::Parser as _;
use syn::spanned::Spanned;
use syn::{Error, FnArg, Ident, ItemFn, LitStr, Pat, Type, Visibility};

// One "did you mean" for the whole crate: it is Damerau-Levenshtein, so
// `hihg` for `high` and `retires` for `retries` — a transposition, the most
// common way a `#[job]` argument gets mistyped — cost one edit rather than two
// and are therefore inside the suggestion budget.
use crate::util::attrs::did_you_mean;

/// Every key `#[job(…)]` accepts, in the order the help line lists them.
const KNOWN_ARGS: &[&str] = &[
    "name",
    "queue",
    "retries",
    "backoff",
    "timeout",
    "unique_for",
    "priority",
    "serial",
    "type_name",
];

/// The `help:` line that follows any argument mistake.
const ARGS_HELP: &str = "help: valid arguments are `name = \"…\"`, `queue = \"…\"`, \
                         `retries = 5`, `backoff = \"exponential(30s, max = 1h)\"`, \
                         `timeout = \"2m\"`, `unique_for = \"10m\"`, `priority = \"high\"`, \
                         `serial` and `type_name = \"…\"`";

/// Expand `#[job(…)] async fn …`.
pub fn expand(args: TokenStream, item: TokenStream) -> TokenStream {
    match try_expand(args, item.clone()) {
        Ok(tokens) => tokens,
        // The user's function is emitted alongside the error so that every
        // *other* mistake in the file is still reported: dropping it would
        // produce a cascade of "cannot find function" errors pointing nowhere
        // near the actual problem.
        Err(error) => {
            let compile_error = error.to_compile_error();
            quote! { #item #compile_error }
        }
    }
}

/// The fallible half of [`expand`].
fn try_expand(args: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let function: ItemFn = syn::parse2(item)?;
    let options = Options::parse(args)?;
    let parts = Parts::of(&function)?;

    let vis = widen(&function.vis);
    let fn_name = &function.sig.ident;
    let type_name = match &options.type_name {
        Some(name) => Ident::new(&name.value(), name.span()),
        None => format_ident!(
            "{}",
            pascal_case(&fn_name.to_string()),
            span = fn_name.span()
        ),
    };
    let wire_name = options
        .name
        .clone()
        .unwrap_or_else(|| LitStr::new(&fn_name.to_string(), fn_name.span()));

    let doc = format!(
        "The [`{fn_name}`] job.\n\n\
         Generated by `#[job]`. Enqueue it with `{type_name}::enqueue(&jobs, args)`, or \
         inside a transaction with `tx.enqueue({type_name}, args)`.\n\n\
         Its wire name is `{}`, which is stable across refactors: renaming the function \
         would orphan every queued row, so `#[job(name = \"…\")]` pins it when the function \
         moves.",
        wire_name.value()
    );

    let payload = &parts.payload;
    let queue = options
        .queue
        .clone()
        .unwrap_or_else(|| LitStr::new("default", Span::call_site()));

    let retries = match &options.retries {
        Some(retries) => quote! { #retries },
        None => quote! { ::moso::__private::DEFAULT_RETRIES },
    };
    let timeout = match &options.timeout {
        Some(literal) => {
            let millis = duration_millis(literal)?;
            quote! { ::core::time::Duration::from_millis(#millis) }
        }
        None => quote! { ::moso::__private::DEFAULT_TIMEOUT },
    };
    let unique_for = match &options.unique_for {
        Some(literal) => {
            let millis = duration_millis(literal)?;
            quote! { ::core::option::Option::Some(::core::time::Duration::from_millis(#millis)) }
        }
        None => quote! { ::core::option::Option::None },
    };
    let backoff = match &options.backoff {
        Some(literal) => backoff_tokens(literal)?,
        None => quote! { ::moso::__private::Backoff::default_exponential() },
    };
    let priority = match &options.priority {
        Some(literal) => priority_tokens(literal)?,
        None => quote! { ::moso::__private::Priority::Normal },
    };
    let serial = options.serial;

    // One `let` per `Inject(..)` parameter, in the order they were written, so
    // the call below can pass them positionally.
    let injections: Vec<TokenStream> = parts
        .injects
        .iter()
        .enumerate()
        .map(|(index, inject)| {
            let binding = format_ident!("__moso_inject_{index}");
            let ty = &inject.inner;
            let span = inject.span;
            if inject.is_dyn {
                quote_spanned! {span=>
                    let #binding = ::moso::__private::Inject(
                        ::moso::__private::JobCtx::inject_dyn::<#ty>(&__moso_ctx)?
                    );
                }
            } else {
                quote_spanned! {span=>
                    let #binding = ::moso::__private::Inject(
                        ::moso::__private::JobCtx::inject::<#ty>(&__moso_ctx)?
                    );
                }
            }
        })
        .collect();

    let call_args: Vec<TokenStream> = {
        let mut out = vec![quote! { __moso_args }];
        for index in 0..parts.injects.len() {
            let binding = format_ident!("__moso_inject_{index}");
            out.push(quote! { #binding });
        }
        if parts.takes_ctx {
            out.push(quote! { __moso_ctx });
        }
        out
    };

    // The `ctx` binding is consumed by the call when the body asked for it, so
    // the injections have to be resolved first either way.
    let ctx_binding = if parts.takes_ctx {
        quote! { let __moso_ctx = __moso_ctx; }
    } else {
        quote! { let _ = &__moso_ctx; }
    };

    Ok(quote! {
        #function

        #[doc = #doc]
        #[derive(::core::clone::Clone, ::core::marker::Copy, ::core::fmt::Debug, ::core::default::Default)]
        #vis struct #type_name;

        impl ::moso::__private::Job for #type_name {
            type Args = #payload;

            const NAME: &'static str = #wire_name;
            const QUEUE: &'static str = #queue;
            const RETRIES: u32 = #retries;
            const TIMEOUT: ::core::time::Duration = #timeout;
            const UNIQUE_FOR: ::core::option::Option<::core::time::Duration> = #unique_for;
            const PRIORITY: ::moso::__private::Priority = #priority;
            const SERIAL: bool = #serial;
            const BACKOFF: ::moso::__private::Backoff = #backoff;

            async fn run(
                __moso_args: Self::Args,
                __moso_ctx: ::moso::__private::JobCtx,
            ) -> ::moso::__private::JobResult {
                #(#injections)*
                #ctx_binding
                #fn_name(#(#call_args),*).await
            }
        }
    })
}

/// Everything `#[job(…)]` was given.
#[derive(Default)]
struct Options {
    /// `name = "…"` — the wire name, pinned.
    name: Option<LitStr>,
    /// `type_name = "…"` — the generated struct's name.
    type_name: Option<LitStr>,
    /// `queue = "…"`.
    queue: Option<LitStr>,
    /// `retries = 5`.
    retries: Option<syn::LitInt>,
    /// `backoff = "exponential(30s, max = 1h)"`.
    backoff: Option<LitStr>,
    /// `timeout = "2m"`.
    timeout: Option<LitStr>,
    /// `unique_for = "10m"`.
    unique_for: Option<LitStr>,
    /// `priority = "high"`.
    priority: Option<LitStr>,
    /// `serial`.
    serial: bool,
}

impl Options {
    /// Parse the attribute's arguments.
    fn parse(args: TokenStream) -> syn::Result<Self> {
        let mut options = Self::default();
        if args.is_empty() {
            return Ok(options);
        }

        let parser = syn::meta::parser(|meta| {
            let key = meta
                .path
                .get_ident()
                .map(ToString::to_string)
                .unwrap_or_default();
            match key.as_str() {
                "name" => options.name = Some(meta.value()?.parse()?),
                "type_name" => options.type_name = Some(meta.value()?.parse()?),
                "queue" => options.queue = Some(meta.value()?.parse()?),
                "retries" => options.retries = Some(meta.value()?.parse()?),
                "backoff" => options.backoff = Some(meta.value()?.parse()?),
                "timeout" => options.timeout = Some(meta.value()?.parse()?),
                "unique_for" => options.unique_for = Some(meta.value()?.parse()?),
                "priority" => options.priority = Some(meta.value()?.parse()?),
                "serial" => options.serial = true,
                other => {
                    let suggestion = did_you_mean(other, KNOWN_ARGS)
                        .map(|near| format!("\nhelp: did you mean `{near}`?"))
                        .unwrap_or_default();
                    return Err(meta.error(format!(
                        "`{other}` is not a `#[job]` argument{suggestion}\n{ARGS_HELP}"
                    )));
                }
            }
            Ok(())
        });
        parser.parse2(args)?;
        Ok(options)
    }
}

/// One `Inject(..)` parameter.
struct Injection {
    /// The `T` of `Inject<T>`.
    inner: Type,
    /// Whether it is a `dyn Trait`, which resolves through `inject_dyn`.
    is_dyn: bool,
    /// The parameter's span, so a missing provider underlines the parameter.
    span: Span,
}

/// The shape of the user's function, once it has been checked.
struct Parts {
    /// The payload type — the first parameter.
    payload: Type,
    /// Every `Inject(..)`, in order.
    injects: Vec<Injection>,
    /// Whether the last parameter is a `JobCtx`.
    takes_ctx: bool,
}

impl Parts {
    /// Read the signature, rejecting everything the grammar does not allow.
    fn of(function: &ItemFn) -> syn::Result<Self> {
        if function.sig.asyncness.is_none() {
            return Err(Error::new(
                function.sig.fn_token.span(),
                "a job body must be `async`\n\
                 help: write `async fn` — a job that blocks the runtime stops every other job \
                 on the same worker, and `Job::run` returns a future",
            ));
        }
        if !function.sig.generics.params.is_empty() {
            return Err(Error::new(
                function.sig.generics.span(),
                "a job body cannot be generic\n\
                 help: `Job` is implemented for one concrete type, and the queue stores one \
                 wire name; a generic job would need one registration per instantiation\n\
                 help: take the varying part in the payload instead",
            ));
        }

        let mut inputs = function.sig.inputs.iter();
        let Some(first) = inputs.next() else {
            return Err(Error::new(
                function.sig.paren_token.span.join(),
                "a job body needs a payload parameter\n\
                 help: `async fn nightly_cleanup(args: (), ctx: JobCtx) -> Result` — the unit \
                 payload is how a job with nothing to carry is written",
            ));
        };

        let payload = match first {
            FnArg::Receiver(receiver) => {
                return Err(Error::new(
                    receiver.span(),
                    "a job body cannot take `self`\n\
                     help: a job is a free function; state comes from `Inject(..)`",
                ));
            }
            FnArg::Typed(typed) => {
                if is_inject(&typed.ty).is_some() || is_ctx(&typed.ty) {
                    return Err(Error::new(
                        typed.span(),
                        "the first parameter of a job body is its payload\n\
                         help: `async fn send_welcome(args: SendWelcome, Inject(db): Inject<Db>, \
                         ctx: JobCtx)` — the payload comes first because it is what the queue \
                         row carries\n\
                         help: a job with no payload takes `args: ()`",
                    ));
                }
                (*typed.ty).clone()
            }
        };

        let mut injects = Vec::new();
        let mut takes_ctx = false;
        for input in inputs {
            let FnArg::Typed(typed) = input else {
                return Err(Error::new(input.span(), "a job body cannot take `self`"));
            };
            if takes_ctx {
                return Err(Error::new(
                    typed.span(),
                    "`ctx: JobCtx` must be the last parameter\n\
                     help: move it after every `Inject(..)`",
                ));
            }
            if is_ctx(&typed.ty) {
                takes_ctx = true;
                continue;
            }
            match is_inject(&typed.ty) {
                Some(inner) => {
                    let is_dyn = matches!(inner, Type::TraitObject(_));
                    // `Inject(db): Inject<Db>` is the spelling every handler
                    // uses; a bare `db: Inject<Db>` works too, and anything
                    // else would silently bind the wrong thing.
                    if let Pat::Ident(_) | Pat::TupleStruct(_) = &*typed.pat {
                    } else {
                        return Err(Error::new(
                            typed.pat.span(),
                            "an `Inject` parameter is destructured as `Inject(name)`\n\
                             help: write `Inject(db): Inject<Db>`, the same spelling a handler \
                             uses",
                        ));
                    }
                    injects.push(Injection {
                        inner,
                        is_dyn,
                        span: typed.ty.span(),
                    });
                }
                None => {
                    return Err(Error::new(
                        typed.span(),
                        "a job body takes a payload, `Inject(..)` parameters and an optional \
                         `ctx: JobCtx`, and nothing else\n\
                         help: there is no request here, so there is nothing to extract — \
                         `Json`, `Query`, `Path` and `Depends` have no meaning in a job\n\
                         help: whatever this parameter carried belongs in the payload, which \
                         is the only thing the queue row stores",
                    ));
                }
            }
        }

        Ok(Self {
            payload,
            injects,
            takes_ctx,
        })
    }
}

/// The `T` of an `Inject<T>` parameter.
fn is_inject(ty: &Type) -> Option<Type> {
    let Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    if segment.ident != "Inject" {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    args.args.iter().find_map(|arg| match arg {
        syn::GenericArgument::Type(inner) => Some(inner.clone()),
        _ => None,
    })
}

/// Whether a parameter is the `JobCtx`.
fn is_ctx(ty: &Type) -> bool {
    let Type::Path(path) = ty else {
        return false;
    };
    path.path
        .segments
        .last()
        .is_some_and(|segment| segment.ident == "JobCtx")
}

/// Widen a private function's visibility to `pub(crate)`.
///
/// A job is almost always registered from a different module than the one that
/// defines it, so a private generated type would be unusable exactly where it
/// is needed. The same rule `#[middleware]` applies, for the same reason.
fn widen(vis: &Visibility) -> TokenStream {
    match vis {
        Visibility::Inherited => quote! { pub(crate) },
        other => other.to_token_stream(),
    }
}

/// `send_welcome_email` becomes `SendWelcomeEmail`.
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut capitalise = true;
    for c in name.chars() {
        if c == '_' {
            capitalise = true;
            continue;
        }
        if capitalise {
            out.extend(c.to_uppercase());
            capitalise = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Parse a `humantime` duration literal at expansion time.
///
/// Done here rather than at runtime so that `timeout = "2 minuts"` is a compile
/// error on the attribute's own span, which is where the mistake is.
fn duration_millis(literal: &LitStr) -> syn::Result<u64> {
    let text = literal.value();
    let duration = parse_humantime(&text).ok_or_else(|| {
        Error::new(
            literal.span(),
            format!(
                "`{text}` is not a duration\n\
                 help: durations are written the way the rest of Moso's configuration writes \
                 them — `30s`, `2m`, `1h`, `500ms`, `1h 30m`"
            ),
        )
    })?;
    u64::try_from(duration).map_err(|_| {
        Error::new(
            literal.span(),
            format!("`{text}` is longer than this attribute can express"),
        )
    })
}

/// A `humantime`-compatible duration parser, in milliseconds.
///
/// A proc-macro crate must not depend on a runtime crate (dependency rule 1),
/// and pulling `humantime` in for one function would put it on every
/// proc-macro build. The grammar is small and the units are the same ones
/// `moso_jobs::Backoff::parse` accepts at runtime, which a test in this file
/// pins.
fn parse_humantime(text: &str) -> Option<u128> {
    let mut total: u128 = 0;
    let mut number: Option<u128> = None;
    let mut unit = String::new();

    let flush = |number: &mut Option<u128>, unit: &mut String, total: &mut u128| -> Option<()> {
        let value = (*number)?;
        let millis = match unit.as_str() {
            "ms" | "msec" | "msecs" | "millis" | "millisecond" | "milliseconds" => 1,
            "s" | "sec" | "secs" | "second" | "seconds" => 1_000,
            "m" | "min" | "mins" | "minute" | "minutes" => 60_000,
            "h" | "hr" | "hrs" | "hour" | "hours" => 3_600_000,
            "d" | "day" | "days" => 86_400_000,
            "w" | "week" | "weeks" => 604_800_000,
            _ => return None,
        };
        *total = total.checked_add(value.checked_mul(millis)?)?;
        *number = None;
        unit.clear();
        Some(())
    };

    for c in text.chars() {
        if c.is_ascii_digit() {
            if !unit.is_empty() {
                flush(&mut number, &mut unit, &mut total)?;
            }
            number = Some(
                number
                    .unwrap_or(0)
                    .checked_mul(10)?
                    .checked_add(u128::from(c.to_digit(10).unwrap_or(0)))?,
            );
        } else if c.is_ascii_alphabetic() {
            // A unit with no number in front of it — `"s"`, `"1h m"` — is not a
            // duration.
            number?;
            unit.push(c);
        } else if c.is_whitespace() {
            if !unit.is_empty() {
                flush(&mut number, &mut unit, &mut total)?;
            }
        } else {
            return None;
        }
    }
    if !unit.is_empty() {
        flush(&mut number, &mut unit, &mut total)?;
    }
    if number.is_some() {
        // A bare number with no unit: `timeout = "120"` is a mistake that would
        // otherwise silently mean 120 milliseconds or 120 seconds depending on
        // who reads it.
        return None;
    }
    Some(total)
}

/// Turn a backoff spec into the `const BACKOFF` expression.
///
/// Parsed here so `backoff = "exponentail(30s)"` is a compile error on the
/// attribute rather than a runtime one at the first retry.
fn backoff_tokens(literal: &LitStr) -> syn::Result<TokenStream> {
    let text = literal.value();
    let trimmed = text.trim();
    let bad = |detail: &str| {
        Error::new(
            literal.span(),
            format!(
                "`{text}` is not a backoff policy: {detail}\n\
                 help: one of `immediate`, `fixed(30s)`, `linear(30s, max = 1h)` or \
                 `exponential(30s, max = 1h)`"
            ),
        )
    };

    if trimmed.eq_ignore_ascii_case("immediate") {
        return Ok(quote! { ::moso::__private::Backoff::Immediate });
    }

    let (name, rest) = trimmed
        .split_once('(')
        .ok_or_else(|| bad("it has no arguments"))?;
    let arguments = rest
        .strip_suffix(')')
        .ok_or_else(|| bad("the closing parenthesis is missing"))?;

    let mut parts = arguments.split(',');
    let base_text = parts.next().unwrap_or_default().trim();
    let base =
        parse_humantime(base_text).ok_or_else(|| bad("the first argument is not a duration"))?;
    let base = u64::try_from(base).map_err(|_| bad("the first argument is too long"))?;

    let max = match parts.next() {
        Some(part) => {
            let value = part
                .trim()
                .strip_prefix("max")
                .and_then(|rest| rest.trim_start().strip_prefix('='))
                .ok_or_else(|| bad("the second argument must be written `max = 1h`"))?;
            let millis =
                parse_humantime(value.trim()).ok_or_else(|| bad("`max` is not a duration"))?;
            Some(u64::try_from(millis).map_err(|_| bad("`max` is too long"))?)
        }
        None => None,
    };
    if parts.next().is_some() {
        return Err(bad("it has more than two arguments"));
    }

    let hour: u64 = 3_600_000;
    Ok(match name.trim() {
        "fixed" => {
            if max.is_some() {
                return Err(bad("`fixed` has no ceiling, so `max` is meaningless"));
            }
            quote! {
                ::moso::__private::Backoff::Fixed {
                    delay: ::core::time::Duration::from_millis(#base),
                }
            }
        }
        "linear" => {
            let max = max.unwrap_or(hour);
            quote! {
                ::moso::__private::Backoff::Linear {
                    base: ::core::time::Duration::from_millis(#base),
                    max: ::core::time::Duration::from_millis(#max),
                }
            }
        }
        "exponential" => {
            let max = max.unwrap_or(hour);
            quote! {
                ::moso::__private::Backoff::Exponential {
                    base: ::core::time::Duration::from_millis(#base),
                    max: ::core::time::Duration::from_millis(#max),
                }
            }
        }
        other => return Err(bad(&format!("`{other}` is not one of the four"))),
    })
}

/// Turn a priority name into the `const PRIORITY` expression.
fn priority_tokens(literal: &LitStr) -> syn::Result<TokenStream> {
    let text = literal.value();
    Ok(match text.trim().to_ascii_lowercase().as_str() {
        "low" => quote! { ::moso::__private::Priority::Low },
        "normal" => quote! { ::moso::__private::Priority::Normal },
        "high" => quote! { ::moso::__private::Priority::High },
        "critical" => quote! { ::moso::__private::Priority::Critical },
        other => {
            let suggestion = did_you_mean(other, &["low", "normal", "high", "critical"])
                .map(|near| format!("\nhelp: did you mean `{near}`?"))
                .unwrap_or_default();
            return Err(Error::new(
                literal.span(),
                format!(
                    "`{text}` is not a priority{suggestion}\n\
                     help: the four are `low`, `normal`, `high` and `critical`"
                ),
            ));
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Expand and flatten, so an assertion can look for a substring without
    /// caring how `quote!` spaced it.
    fn expand_to_string(args: TokenStream, item: TokenStream) -> String {
        expand(args, item).to_string().replace(' ', "")
    }

    /// The bare case: a function becomes a type with the documented defaults.
    #[test]
    fn a_bare_job_takes_every_default() {
        let out = expand_to_string(
            quote! {},
            quote! {
                async fn send_welcome_email(args: SendWelcome, ctx: JobCtx) -> Result {
                    Ok(())
                }
            },
        );

        assert!(out.contains("pub(crate)structSendWelcomeEmail;"), "{out}");
        assert!(
            out.contains(r#"constNAME:&'staticstr="send_welcome_email""#),
            "{out}"
        );
        assert!(out.contains(r#"constQUEUE:&'staticstr="default""#), "{out}");
        assert!(
            out.contains("constRETRIES:u32=::moso::__private::DEFAULT_RETRIES"),
            "{out}"
        );
        assert!(out.contains("::moso::__private::DEFAULT_TIMEOUT"), "{out}");
        assert!(out.contains("constSERIAL:bool=false"), "{out}");
        assert!(out.contains("typeArgs=SendWelcome"), "{out}");
        // The user's function is emitted unchanged, so it stays callable.
        assert!(out.contains("asyncfnsend_welcome_email"), "{out}");
    }

    /// Every argument the documentation's example uses, in one attribute.
    #[test]
    fn the_documented_attribute_sets_every_constant() {
        let out = expand_to_string(
            quote! {
                queue = "mail",
                retries = 5,
                backoff = "exponential(30s, max = 1h)",
                timeout = "2m",
                unique_for = "10m"
            },
            quote! {
                async fn send_welcome_email(args: SendWelcome, ctx: JobCtx) -> Result { Ok(()) }
            },
        );

        assert!(out.contains(r#"constQUEUE:&'staticstr="mail""#), "{out}");
        assert!(out.contains("constRETRIES:u32=5"), "{out}");
        assert!(out.contains("Duration::from_millis(120000u64)"), "{out}");
        assert!(out.contains("Duration::from_millis(600000u64)"), "{out}");
        assert!(out.contains("Backoff::Exponential"), "{out}");
        assert!(out.contains("from_millis(30000u64)"), "{out}");
        assert!(out.contains("from_millis(3600000u64)"), "{out}");
    }

    /// The wire name is the function's own, and `name = "…"` pins it when the
    /// function moves — which is the whole reason it is not the Rust path.
    #[test]
    fn the_wire_name_can_be_pinned_across_a_rename() {
        let out = expand_to_string(
            quote! { name = "send_welcome_email", type_name = "WelcomeMailer" },
            quote! { async fn greet_a_new_user(args: (), ctx: JobCtx) -> Result { Ok(()) } },
        );
        assert!(
            out.contains(r#"constNAME:&'staticstr="send_welcome_email""#),
            "{out}"
        );
        assert!(out.contains("structWelcomeMailer;"), "{out}");
    }

    /// One `ctx.inject` per `Inject(..)`, in the order they were written, and a
    /// `dyn Trait` goes through `inject_dyn`.
    #[test]
    fn each_inject_becomes_one_resolution() {
        let out = expand_to_string(
            quote! {},
            quote! {
                async fn send(
                    args: SendWelcome,
                    Inject(db): Inject<Db>,
                    Inject(mail): Inject<dyn Mailer>,
                    ctx: JobCtx,
                ) -> Result { Ok(()) }
            },
        );
        assert!(out.contains("JobCtx::inject::<Db>(&__moso_ctx)"), "{out}");
        assert!(
            out.contains("JobCtx::inject_dyn::<dynMailer>(&__moso_ctx)"),
            "{out}"
        );
        assert!(
            out.contains("send(__moso_args,__moso_inject_0,__moso_inject_1,__moso_ctx)"),
            "{out}"
        );
    }

    /// A job that does not want the context must still compile, and must not
    /// leave an unused binding behind.
    #[test]
    fn the_context_parameter_is_optional() {
        let out = expand_to_string(
            quote! {},
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(out.contains("tidy(__moso_args)"), "{out}");
        assert!(out.contains("let_=&__moso_ctx;"), "{out}");
    }

    /// A private function's job type is widened, because a job is registered
    /// from a different module than the one that defines it.
    #[test]
    fn visibility_is_widened_to_the_crate() {
        let private = expand_to_string(
            quote! {},
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(private.contains("pub(crate)structTidy;"), "{private}");

        let public = expand_to_string(
            quote! {},
            quote! { pub async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(public.contains("pubstructTidy;"), "{public}");
    }

    /// Every mistake the grammar can catch, with the `help:` line that says
    /// what to write instead.
    #[test]
    fn every_shape_error_names_the_fix() {
        let not_async =
            expand_to_string(quote! {}, quote! { fn tidy(args: ()) -> Result { Ok(()) } });
        assert!(not_async.contains("mustbe`async`"), "{not_async}");

        let generic = expand_to_string(
            quote! {},
            quote! { async fn tidy<T>(args: T) -> Result { Ok(()) } },
        );
        assert!(generic.contains("cannotbegeneric"), "{generic}");

        let no_params =
            expand_to_string(quote! {}, quote! { async fn tidy() -> Result { Ok(()) } });
        assert!(no_params.contains("needsapayloadparameter"), "{no_params}");

        let ctx_first = expand_to_string(
            quote! {},
            quote! { async fn tidy(ctx: JobCtx, args: ()) -> Result { Ok(()) } },
        );
        assert!(ctx_first.contains("isitspayload"), "{ctx_first}");

        let extractor = expand_to_string(
            quote! {},
            quote! { async fn tidy(args: (), Json(body): Json<Thing>) -> Result { Ok(()) } },
        );
        assert!(extractor.contains("thereisnorequesthere"), "{extractor}");

        let ctx_not_last = expand_to_string(
            quote! {},
            quote! {
                async fn tidy(args: (), ctx: JobCtx, Inject(db): Inject<Db>) -> Result { Ok(()) }
            },
        );
        assert!(
            ctx_not_last.contains("mustbethelastparameter"),
            "{ctx_not_last}"
        );
    }

    /// Every argument mistake, with the "did you mean" that turns a typo into a
    /// one-character fix.
    #[test]
    fn every_argument_error_names_the_fix() {
        let unknown = expand_to_string(
            quote! { retires = 5 },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(unknown.contains("didyoumean`retries`"), "{unknown}");

        let bad_duration = expand_to_string(
            quote! { timeout = "2 minuts" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(bad_duration.contains("isnotaduration"), "{bad_duration}");

        let bare_number = expand_to_string(
            quote! { timeout = "120" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(bare_number.contains("isnotaduration"), "{bare_number}");

        let bad_backoff = expand_to_string(
            quote! { backoff = "exponentail(30s)" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(bad_backoff.contains("isnotoneofthefour"), "{bad_backoff}");

        let bad_priority = expand_to_string(
            quote! { priority = "urgent" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(bad_priority.contains("isnotapriority"), "{bad_priority}");
        assert!(
            bad_priority.contains("`low`,`normal`,`high`and`critical`"),
            "{bad_priority}"
        );

        // A one-character typo is close enough to suggest; `urgent` is not, and
        // a suggestion that fires on anything is noise rather than help.
        let near_miss = expand_to_string(
            quote! { priority = "hihg" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(near_miss.contains("didyoumean`high`"), "{near_miss}");
    }

    /// The duration grammar has to agree with the runtime one, or a `timeout`
    /// and a `backoff` written the same way would mean different things.
    #[test]
    fn the_duration_grammar_matches_the_runtime_one() {
        assert_eq!(parse_humantime("500ms"), Some(500));
        assert_eq!(parse_humantime("30s"), Some(30_000));
        assert_eq!(parse_humantime("2m"), Some(120_000));
        assert_eq!(parse_humantime("1h"), Some(3_600_000));
        assert_eq!(parse_humantime("1h 30m"), Some(5_400_000));
        assert_eq!(parse_humantime("1d"), Some(86_400_000));
        assert_eq!(parse_humantime("1w"), Some(604_800_000));
        assert_eq!(parse_humantime("10 minutes"), Some(600_000));

        assert_eq!(parse_humantime(""), Some(0));
        assert_eq!(parse_humantime("120"), None, "a bare number is ambiguous");
        assert_eq!(parse_humantime("2 minuts"), None);
        assert_eq!(parse_humantime("s"), None);
        assert_eq!(parse_humantime("-5s"), None);
    }

    /// The generated type's name is the function's, in Pascal case.
    #[test]
    fn the_type_name_is_the_function_name_in_pascal_case() {
        assert_eq!(pascal_case("send_welcome_email"), "SendWelcomeEmail");
        assert_eq!(pascal_case("tidy"), "Tidy");
        assert_eq!(pascal_case("http_ping"), "HttpPing");
        assert_eq!(pascal_case("_leading"), "Leading");
    }

    /// A `serial` job says so on its type, which is what makes the unique-key
    /// chain ordered.
    #[test]
    fn serial_is_a_bare_flag() {
        let out = expand_to_string(
            quote! { serial, unique_for = "1h" },
            quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
        );
        assert!(out.contains("constSERIAL:bool=true"), "{out}");
    }

    /// The four priorities, since a wrong one silently reorders a queue.
    #[test]
    fn every_priority_maps_to_its_variant() {
        for (written, expected) in [
            ("low", "Priority::Low"),
            ("normal", "Priority::Normal"),
            ("high", "Priority::High"),
            ("CRITICAL", "Priority::Critical"),
        ] {
            let out = expand_to_string(
                quote! { priority = #written },
                quote! { async fn tidy(args: ()) -> Result { Ok(()) } },
            );
            assert!(out.contains(expected), "{written}: {out}");
        }
    }
}
