//! Typed permissions: the [`Permission`] trait, the [`PermSet`] bitset, and the
//! registry that makes the whole set enumerable at boot.
//!
//! # What `permissions!` generates
//!
//! `moso::permissions!` is a proc macro (it has to be: turning `posts.read`
//! into `PostsRead` needs case conversion, which `macro_rules!` cannot do). It
//! lives in `moso-macros`; **this module is the contract it targets**, and the
//! expansion is frozen here so the macro and the runtime can be built in
//! parallel.
//!
//! ```text
//! // written
//! moso::permissions! {
//!     /// Posts
//!     posts.read    = "View posts",
//!     posts.publish = "Publish posts",
//! }
//!
//! // generated
//! #[repr(u16)]
//! #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
//! pub enum Perm { PostsRead, PostsPublish }
//!
//! impl Perm {
//!     pub const ALL: &'static [Perm] = &[Perm::PostsRead, Perm::PostsPublish];
//!     pub const fn as_str(self) -> &'static str { /* "posts.read" */ }
//!     pub const fn description(self) -> &'static str { /* "View posts" */ }
//!     pub const fn group(self) -> &'static str { /* "posts" */ }
//! }
//!
//! impl ::moso::__private::Permission for Perm { /* delegates to the consts */ }
//!
//! // and the compile-time cap check
//! const _: () = assert!(Perm::ALL.len() <= ::moso::__private::MAX_PERMISSIONS);
//! ```
//!
//! # Why the enum is called `Perm` and the trait is not
//!
//! The generated enum lives in the *application's* crate and is named `Perm`,
//! because that is what a call site reads best: `Perm::PostsPublish`. A trait
//! with the same name in this crate would collide in every prelude import, so
//! the trait is [`Permission`] and the erased descriptor is [`PermRef`].
//! Nothing in this crate is called `Perm`, on purpose.

use core::marker::PhantomData;
use std::borrow::Cow;

use serde::{Deserialize, Serialize};

/// The largest permission registry `permissions!` will accept.
///
/// Two hundred and fifty-six is four 64-bit words: a [`PermSet`] stays `Copy`,
/// stays 32 bytes, and a check stays four `AND`s. Raising it means widening
/// every set in every request, which is why it is a constant and not a
/// parameter. An application that needs more has a modelling problem —
/// permissions are capabilities, not rows.
///
/// ```
/// assert_eq!(moso_authz::MAX_PERMISSIONS, 256);
/// ```
pub const MAX_PERMISSIONS: usize = 256;

/// How many 64-bit words a [`PermSet`] occupies.
///
/// ```
/// assert_eq!(moso_authz::perm::PERM_WORDS, 4);
/// ```
pub const PERM_WORDS: usize = MAX_PERMISSIONS / 64;

/// A permission registry: what `permissions!` implements on the generated enum.
///
/// ```no_run
/// use moso_authz::{PermSet, Permission};
///
/// fn describe<P: Permission>(perm: P) -> &'static str {
///     perm.description()
/// }
///
/// fn everything<P: Permission>() -> PermSet<P> {
///     PermSet::all()
/// }
/// ```
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a permission set generated by `permissions!`",
    label = "not a permission",
    note = "the permission enum is generated — write `moso::permissions! {{ posts.read = \"…\" }}` \
            in one module and use the `Perm` it produces",
    note = "help: a hand-written permission enum must implement `Permission`, which needs `ALL`, \
            `index`, `from_index`, `as_str`, `description`, `group` and `parse`",
    note = "help: if you meant the *set* type, that is `PermSet<Perm>`, not `Perm`"
)]
pub trait Permission: Copy + Eq + core::hash::Hash + Send + Sync + 'static {
    /// Every permission, in declaration order. Index `i` is `ALL[i]`.
    const ALL: &'static [Self];

    /// A hash of every permission's name, in order.
    ///
    /// Two processes that agree on this agree on what bit means what, which is
    /// what makes [`PermBits`] safe to send across a boundary. Generated as a
    /// `const`, so the check costs nothing at runtime.
    const FINGERPRINT: u64;

    /// This permission's index, which is its bit in a [`PermSet`].
    fn index(self) -> u16;

    /// The permission at `index`, or `None` when nothing is registered there.
    fn from_index(index: u16) -> Option<Self>;

    /// The wire name, e.g. `"posts.publish"`.
    ///
    /// The generated enum also has an inherent `const fn as_str`; this method
    /// delegates to it. Trait methods cannot be `const` on stable, and the
    /// `const` version is what a `match` arm in user code wants.
    fn as_str(self) -> &'static str;

    /// The human description, from the right-hand side of the declaration.
    fn description(self) -> &'static str;

    /// The group, i.e. the part before the dot: `"posts"`.
    fn group(self) -> &'static str;

    /// Parse a wire name back into a permission, for a database round trip.
    fn parse(name: &str) -> Option<Self>;

    /// How many permissions are registered.
    #[must_use]
    fn count() -> usize {
        Self::ALL.len()
    }
}

/// A compact set of permissions.
///
/// Four `u64`s: `Copy`, 32 bytes, and a membership test is one shift and one
/// `AND`. Permission checks happen many times per request — an
/// `Arc<HashSet<String>>` lookup in a hot loop is exactly how authorization
/// becomes the thing a profiler points at.
///
/// ```no_run
/// use moso_authz::{PermSet, Permission};
///
/// fn combine<P: Permission>(a: PermSet<P>, b: PermSet<P>) -> PermSet<P> {
///     a.union(b)
/// }
/// ```
pub struct PermSet<P: Permission> {
    /// The bits. Bit `i` of word `i / 64` is `P::ALL[i]`.
    words: [u64; PERM_WORDS],
    /// The permission type, which holds no data.
    marker: PhantomData<fn() -> P>,
}

impl<P: Permission> PermSet<P> {
    /// The empty set.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>() { let _: PermSet<P> = PermSet::empty(); }
    /// ```
    #[must_use]
    pub const fn empty() -> Self {
        Self {
            words: [0; PERM_WORDS],
            marker: PhantomData,
        }
    }

    /// Every registered permission.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>() { let _: PermSet<P> = PermSet::all(); }
    /// ```
    #[must_use]
    pub fn all() -> Self {
        let mut set = Self::empty();
        for permission in P::ALL.iter().copied() {
            set = set.with(permission);
        }
        set
    }

    /// A set from raw words, without a fingerprint check.
    ///
    /// `const`, which is what lets `roles!` emit a role's permissions as a
    /// constant and makes static role resolution free. Prefer
    /// [`from_bits`](PermSet::from_bits) anywhere the words crossed a boundary:
    /// this constructor trusts them.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>() { let _: PermSet<P> = PermSet::from_words([1, 0, 0, 0]); }
    /// ```
    #[must_use]
    pub const fn from_words(words: [u64; PERM_WORDS]) -> Self {
        Self {
            words,
            marker: PhantomData,
        }
    }

    /// Set one bit by index, in a `const` context.
    ///
    /// The `const` half of [`with`](PermSet::with). `roles!` emits
    /// `PermSet::empty().with_index(Perm::PostsRead as u16)…` because
    /// [`Permission::index`] is a trait method and trait methods cannot be
    /// `const` on stable, while `Perm::Variant as u16` can.
    ///
    /// An index at or past [`MAX_PERMISSIONS`] is ignored, for the same
    /// fail-closed reason [`has`](PermSet::has) returns `false` for one.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>() { let _: PermSet<P> = PermSet::empty().with_index(3); }
    /// ```
    #[must_use]
    pub const fn with_index(mut self, index: u16) -> Self {
        let index = index as usize;
        if index < MAX_PERMISSIONS {
            self.words[index / 64] |= 1u64 << (index % 64);
        }
        self
    }

    /// The raw words, without the fingerprint.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _ = s.words(); }
    /// ```
    #[must_use]
    pub const fn words(self) -> [u64; PERM_WORDS] {
        self.words
    }

    /// A set holding exactly the given permissions.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: P, b: P) { let _ = PermSet::of([a, b]); }
    /// ```
    #[must_use]
    pub fn of(permissions: impl IntoIterator<Item = P>) -> Self {
        permissions
            .into_iter()
            .fold(Self::empty(), |set, permission| set.with(permission))
    }

    /// Add a permission, returning the new set.
    ///
    /// Takes and returns by value because the set is `Copy`; a builder that
    /// mutated in place would be slower and no clearer.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(p: P) { let _ = PermSet::empty().with(p); }
    /// ```
    #[must_use]
    pub fn with(mut self, permission: P) -> Self {
        if let Some((word, bit)) = position(permission.index()) {
            self.words[word] |= bit;
        }
        self
    }

    /// Remove a permission, returning the new set.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>, p: P) { let _ = s.without(p); }
    /// ```
    #[must_use]
    pub fn without(mut self, permission: P) -> Self {
        if let Some((word, bit)) = position(permission.index()) {
            self.words[word] &= !bit;
        }
        self
    }

    /// Whether the set holds `permission`. One shift, one `AND`.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>, p: P) { let _: bool = s.has(p); }
    /// ```
    #[must_use]
    pub fn has(self, permission: P) -> bool {
        match position(permission.index()) {
            Some((word, bit)) => self.words[word] & bit != 0,
            None => false,
        }
    }

    /// Whether the set holds every permission in `other`.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: PermSet<P>, b: PermSet<P>) { let _: bool = a.has_all(b); }
    /// ```
    #[must_use]
    pub fn has_all(self, other: Self) -> bool {
        let mut index = 0;
        while index < PERM_WORDS {
            if other.words[index] & !self.words[index] != 0 {
                return false;
            }
            index += 1;
        }
        true
    }

    /// Whether the set holds any permission in `other`.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: PermSet<P>, b: PermSet<P>) { let _: bool = a.has_any(b); }
    /// ```
    #[must_use]
    pub fn has_any(self, other: Self) -> bool {
        let mut index = 0;
        while index < PERM_WORDS {
            if self.words[index] & other.words[index] != 0 {
                return true;
            }
            index += 1;
        }
        false
    }

    /// Everything in either set.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: PermSet<P>, b: PermSet<P>) { let _ = a.union(b); }
    /// ```
    #[must_use]
    pub fn union(self, other: Self) -> Self {
        self.zip_with(other, |left, right| left | right)
    }

    /// Everything in both sets.
    ///
    /// This is what an API key's scopes do to a user's permissions: the key can
    /// never grant more than the user has.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: PermSet<P>, b: PermSet<P>) { let _ = a.intersection(b); }
    /// ```
    #[must_use]
    pub fn intersection(self, other: Self) -> Self {
        self.zip_with(other, |left, right| left & right)
    }

    /// Everything in this set that is not in `other`.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(a: PermSet<P>, b: PermSet<P>) { let _ = a.difference(b); }
    /// ```
    #[must_use]
    pub fn difference(self, other: Self) -> Self {
        self.zip_with(other, |left, right| left & !right)
    }

    /// Combine two sets word by word. The one place the bitwise operators live.
    fn zip_with(mut self, other: Self, combine: fn(u64, u64) -> u64) -> Self {
        let mut index = 0;
        while index < PERM_WORDS {
            self.words[index] = combine(self.words[index], other.words[index]);
            index += 1;
        }
        self
    }

    /// How many permissions the set holds.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _: usize = s.len(); }
    /// ```
    #[must_use]
    pub fn len(self) -> usize {
        self.words
            .iter()
            .map(|word| word.count_ones() as usize)
            .sum()
    }

    /// Whether the set is empty.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _: bool = s.is_empty(); }
    /// ```
    #[must_use]
    pub fn is_empty(self) -> bool {
        self.words.iter().all(|word| *word == 0)
    }

    /// The permissions in the set, in registry order.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _: Vec<P> = s.iter().collect(); }
    /// ```
    pub fn iter(self) -> impl Iterator<Item = P> {
        // Walking `P::ALL` rather than the words costs one test per *registered*
        // permission instead of one per bit, and yields registry order for free.
        P::ALL
            .iter()
            .copied()
            .filter(move |permission| self.has(*permission))
    }

    /// The wire names, in registry order. For a database round trip, an API
    /// key's scope list, and the admin's role editor.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _: Vec<&'static str> = s.names(); }
    /// ```
    #[must_use]
    pub fn names(self) -> Vec<&'static str> {
        self.iter().map(Permission::as_str).collect()
    }

    /// Parse a set from wire names, ignoring anything unregistered.
    ///
    /// Ignoring rather than failing is deliberate: a permission removed in a
    /// deploy must not stop every stored API key from being usable. The count
    /// of ignored names is returned so the caller can log it.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Permission};
    /// # fn f<P: Permission>(names: &[String]) {
    /// let (set, unknown): (PermSet<P>, usize) = PermSet::parse_all(names);
    /// let _ = (set, unknown);
    /// # }
    /// ```
    #[must_use]
    pub fn parse_all<S: AsRef<str>>(names: &[S]) -> (Self, usize) {
        let mut set = Self::empty();
        let mut unknown = 0;
        for name in names {
            match P::parse(name.as_ref()) {
                Some(permission) => set = set.with(permission),
                None => unknown += 1,
            }
        }
        (set, unknown)
    }

    /// The raw words, with the registry fingerprint that validates them.
    ///
    /// The bridge to anything that cannot name `P`: an API key's stored scopes,
    /// a cached role resolution, an audit record.
    ///
    /// ```no_run
    /// # use moso_authz::{PermBits, PermSet, Permission};
    /// # fn f<P: Permission>(s: PermSet<P>) { let _: PermBits = s.to_bits(); }
    /// ```
    #[must_use]
    pub fn to_bits(self) -> PermBits {
        PermBits::new(self.words, P::FINGERPRINT)
    }

    /// Recover a typed set from raw words.
    ///
    /// # Errors
    ///
    /// [`Error::UnknownPermission`](crate::Error::UnknownPermission) when the
    /// fingerprint does not match `P` — which means the bits came from a
    /// different registry and every bit would mean the wrong thing.
    ///
    /// ```no_run
    /// # use moso_authz::{PermBits, PermSet, Permission};
    /// # fn f<P: Permission>(b: PermBits) -> moso_authz::Result<PermSet<P>> {
    /// PermSet::from_bits(b)
    /// # }
    /// ```
    pub fn from_bits(bits: PermBits) -> crate::Result<Self> {
        if bits.fingerprint() != P::FINGERPRINT {
            return Err(crate::Error::UnknownPermission {
                name: format!(
                    "<{} bits from registry {:#018x}, expected {:#018x}>",
                    bits.len(),
                    bits.fingerprint(),
                    P::FINGERPRINT,
                ),
                suggestion: None,
            });
        }
        Ok(Self {
            words: bits.words(),
            marker: PhantomData,
        })
    }
}

/// The word and mask a permission index addresses, or `None` when the index is
/// outside [`MAX_PERMISSIONS`].
///
/// Out of range is `None` rather than a panic: the index comes from
/// [`Permission::index`], which a hand-written enum implements, and a framework
/// has no business aborting a request over somebody else's arithmetic. A bit
/// that cannot exist is a bit that is not set, which fails closed.
const fn position(index: u16) -> Option<(usize, u64)> {
    let index = index as usize;
    if index >= MAX_PERMISSIONS {
        return None;
    }
    Some((index / 64, 1u64 << (index % 64)))
}

impl<P: Permission> Clone for PermSet<P> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<P: Permission> Copy for PermSet<P> {}

impl<P: Permission> Default for PermSet<P> {
    fn default() -> Self {
        Self::empty()
    }
}

impl<P: Permission> PartialEq for PermSet<P> {
    fn eq(&self, other: &Self) -> bool {
        self.words == other.words
    }
}

impl<P: Permission> Eq for PermSet<P> {}

impl<P: Permission> core::hash::Hash for PermSet<P> {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        self.words.hash(state);
    }
}

impl<P: Permission> core::fmt::Debug for PermSet<P> {
    /// Prints the names, not the words. A bitset in a log is unreadable, and
    /// the whole point of a typed registry is that the names exist.
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("PermSet{")?;
        for (position, name) in self.names().into_iter().enumerate() {
            if position > 0 {
                f.write_str(", ")?;
            }
            f.write_str(name)?;
        }
        f.write_str("}")
    }
}

impl<P: Permission> FromIterator<P> for PermSet<P> {
    fn from_iter<I: IntoIterator<Item = P>>(iter: I) -> Self {
        Self::of(iter)
    }
}

/// A [`PermSet`] with its type erased, plus the fingerprint that proves which
/// registry it came from.
///
/// Used where `P` cannot be named: an API key's stored scopes, a KV-cached role
/// resolution, an audit record, and the `PermissionSource` a `#[requires]`
/// guard consults.
///
/// ```no_run
/// use moso_authz::PermBits;
///
/// # fn f(b: PermBits) {
/// let _: u64 = b.fingerprint();
/// # }
/// ```
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PermBits {
    /// The bits.
    words: [u64; PERM_WORDS],
    /// Which registry produced them.
    fingerprint: u64,
}

impl PermBits {
    /// Raw words and the registry they belong to.
    ///
    /// ```no_run
    /// use moso_authz::PermBits;
    ///
    /// let _ = PermBits::new([0; moso_authz::perm::PERM_WORDS], 0);
    /// ```
    #[must_use]
    pub const fn new(words: [u64; PERM_WORDS], fingerprint: u64) -> Self {
        Self { words, fingerprint }
    }

    /// Which registry these bits belong to.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _: u64 = b.fingerprint(); }
    /// ```
    #[must_use]
    pub const fn fingerprint(self) -> u64 {
        self.fingerprint
    }

    /// The raw words.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _ = b.words(); }
    /// ```
    #[must_use]
    pub const fn words(self) -> [u64; PERM_WORDS] {
        self.words
    }

    /// Whether the bit at `index` is set, without knowing the registry.
    ///
    /// The primitive a `#[requires]` guard uses: the required set and the
    /// actor's set are compared as bits, after their fingerprints matched.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _: bool = b.has_index(3); }
    /// ```
    #[must_use]
    pub fn has_index(self, index: u16) -> bool {
        match position(index) {
            Some((word, bit)) => self.words[word] & bit != 0,
            None => false,
        }
    }

    /// How many bits are set.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _: usize = b.len(); }
    /// ```
    #[must_use]
    pub fn len(self) -> usize {
        self.words
            .iter()
            .map(|word| word.count_ones() as usize)
            .sum()
    }

    /// Whether no bit is set.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _: bool = b.is_empty(); }
    /// ```
    #[must_use]
    pub fn is_empty(self) -> bool {
        self.words.iter().all(|word| *word == 0)
    }

    /// Whether every bit set in `other` is set here.
    ///
    /// The primitive behind `#[requires(a, b)]`, which needs *both*. The
    /// fingerprints must already have been compared: two sets of bits from
    /// different registries compare cleanly and mean nothing.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(a: PermBits, b: PermBits) { let _: bool = a.has_all(b); }
    /// ```
    #[must_use]
    pub fn has_all(self, other: Self) -> bool {
        (0..PERM_WORDS).all(|index| other.words[index] & !self.words[index] == 0)
    }

    /// Whether any bit set in `other` is set here.
    ///
    /// The primitive behind `#[requires(any(a, b))]`.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(a: PermBits, b: PermBits) { let _: bool = a.has_any(b); }
    /// ```
    #[must_use]
    pub fn has_any(self, other: Self) -> bool {
        (0..PERM_WORDS).any(|index| self.words[index] & other.words[index] != 0)
    }

    /// The indices that are set, in ascending order.
    ///
    /// ```no_run
    /// # use moso_authz::PermBits;
    /// # fn f(b: PermBits) { let _: Vec<u16> = b.indices().collect(); }
    /// ```
    pub fn indices(self) -> impl Iterator<Item = u16> {
        (0..MAX_PERMISSIONS as u16).filter(move |index| self.has_index(*index))
    }
}

/// One permission, described without naming its enum.
///
/// What the admin's role editor renders, what `moso authz explain` prints, and
/// what the OpenAPI document lists in a 403's description.
///
/// ```
/// use moso_authz::PermRef;
///
/// const READ: PermRef = PermRef::new(0, "posts.read", "View posts", "posts");
/// assert_eq!(READ.group(), "posts");
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PermRef {
    /// Its bit position.
    index: u16,
    /// Its wire name.
    name: Cow<'static, str>,
    /// Its human description.
    description: Cow<'static, str>,
    /// Its group.
    group: Cow<'static, str>,
}

impl PermRef {
    /// Describe a permission.
    ///
    /// ```
    /// use moso_authz::PermRef;
    ///
    /// let _ = PermRef::new(1, "posts.publish", "Publish posts", "posts");
    /// ```
    #[must_use]
    pub const fn new(
        index: u16,
        name: &'static str,
        description: &'static str,
        group: &'static str,
    ) -> Self {
        Self {
            index,
            name: Cow::Borrowed(name),
            description: Cow::Borrowed(description),
            group: Cow::Borrowed(group),
        }
    }

    /// Describe a typed permission.
    ///
    /// ```no_run
    /// # use moso_authz::{PermRef, Permission};
    /// # fn f<P: Permission>(p: P) { let _: PermRef = PermRef::of(p); }
    /// ```
    #[must_use]
    pub fn of<P: Permission>(permission: P) -> Self {
        Self {
            index: permission.index(),
            name: Cow::Borrowed(permission.as_str()),
            description: Cow::Borrowed(permission.description()),
            group: Cow::Borrowed(permission.group()),
        }
    }

    /// Its bit position.
    ///
    /// ```
    /// # use moso_authz::PermRef;
    /// # const P: PermRef = PermRef::new(7, "a.b", "", "a");
    /// assert_eq!(P.index(), 7);
    /// ```
    #[must_use]
    pub const fn index(&self) -> u16 {
        self.index
    }

    /// Its wire name.
    ///
    /// ```
    /// # use moso_authz::PermRef;
    /// # const P: PermRef = PermRef::new(0, "a.b", "", "a");
    /// assert_eq!(P.name(), "a.b");
    /// ```
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Its human description.
    ///
    /// ```
    /// # use moso_authz::PermRef;
    /// # const P: PermRef = PermRef::new(0, "a.b", "Do the thing", "a");
    /// assert_eq!(P.description(), "Do the thing");
    /// ```
    #[must_use]
    pub fn description(&self) -> &str {
        &self.description
    }

    /// Its group.
    ///
    /// ```
    /// # use moso_authz::PermRef;
    /// # const P: PermRef = PermRef::new(0, "a.b", "", "a");
    /// assert_eq!(P.group(), "a");
    /// ```
    #[must_use]
    pub fn group(&self) -> &str {
        &self.group
    }
}

/// The whole permission set, enumerable at boot.
///
/// Design goal 2 of `docs/03-batteries/31-authorization.md`: the admin UI can
/// render it, the OpenAPI can document it, an audit can list it, and
/// `#[requires("posts.pubish")]` can be caught with a suggestion instead of
/// silently never matching.
///
/// ```no_run
/// use moso_authz::{PermissionRegistry, Permission};
///
/// # fn f<P: Permission>() {
/// let registry = PermissionRegistry::of::<P>();
/// assert!(registry.lookup("posts.read").is_some() || registry.all().is_empty());
/// # }
/// ```
#[derive(Clone, Debug)]
pub struct PermissionRegistry {
    /// Every permission, in declaration order.
    entries: Vec<PermRef>,
    /// The fingerprint of the registry these came from.
    fingerprint: u64,
}

impl PermissionRegistry {
    /// Build the registry for a permission type.
    ///
    /// ```no_run
    /// # use moso_authz::{PermissionRegistry, Permission};
    /// # fn f<P: Permission>() { let _ = PermissionRegistry::of::<P>(); }
    /// ```
    #[must_use]
    pub fn of<P: Permission>() -> Self {
        Self {
            entries: P::ALL.iter().copied().map(PermRef::of).collect(),
            fingerprint: P::FINGERPRINT,
        }
    }

    /// Every permission, in declaration order.
    ///
    /// ```no_run
    /// # use moso_authz::{PermRef, PermissionRegistry};
    /// # fn f(r: &PermissionRegistry) { let _: &[PermRef] = r.all(); }
    /// ```
    #[must_use]
    pub fn all(&self) -> &[PermRef] {
        &self.entries
    }

    /// The distinct groups, in first-seen order.
    ///
    /// What the admin's role editor uses for its section headings.
    ///
    /// ```no_run
    /// # use moso_authz::PermissionRegistry;
    /// # fn f(r: &PermissionRegistry) { let _: Vec<&str> = r.groups(); }
    /// ```
    #[must_use]
    pub fn groups(&self) -> Vec<&str> {
        let mut groups: Vec<&str> = Vec::new();
        for entry in &self.entries {
            if !groups.contains(&entry.group()) {
                groups.push(entry.group());
            }
        }
        groups
    }

    /// Every permission in one group, in declaration order.
    ///
    /// What the admin's role editor renders under each section heading.
    ///
    /// ```no_run
    /// # use moso_authz::{PermRef, PermissionRegistry};
    /// # fn f(r: &PermissionRegistry) { let _: Vec<&PermRef> = r.in_group("posts"); }
    /// ```
    #[must_use]
    pub fn in_group(&self, group: &str) -> Vec<&PermRef> {
        self.entries
            .iter()
            .filter(|entry| entry.group() == group)
            .collect()
    }

    /// Look a permission up by wire name.
    ///
    /// ```no_run
    /// # use moso_authz::{PermRef, PermissionRegistry};
    /// # fn f(r: &PermissionRegistry) { let _: Option<PermRef> = r.lookup("posts.read"); }
    /// ```
    #[must_use]
    pub fn lookup(&self, name: &str) -> Option<PermRef> {
        self.entries
            .iter()
            .find(|entry| entry.name() == name)
            .cloned()
    }

    /// The closest registered name to `name`, when one is close enough.
    ///
    /// Levenshtein with the same threshold the rest of Moso's diagnostics use,
    /// so `posts.pubish` suggests `posts.publish` and `xyzzy` suggests nothing.
    ///
    /// ```no_run
    /// # use moso_authz::PermissionRegistry;
    /// # fn f(r: &PermissionRegistry) { let _: Option<&str> = r.suggest("posts.pubish"); }
    /// ```
    #[must_use]
    pub fn suggest(&self, name: &str) -> Option<&str> {
        let budget = (name.chars().count() / 3).max(1) + 1;
        self.entries
            .iter()
            .map(|entry| (edit_distance(name, entry.name()), entry.name()))
            .filter(|(distance, _)| *distance <= budget)
            .min_by_key(|(distance, candidate)| (*distance, candidate.len()))
            .map(|(_, candidate)| candidate)
    }

    /// Check that every name in `required` is registered.
    ///
    /// What a boot check calls for a `#[requires("posts.pubish")]` written as a
    /// string rather than as an enum variant. Every unknown name is reported,
    /// not just the first, because a boot error that reports one problem at a
    /// time makes people fix them one at a time.
    ///
    /// # Errors
    ///
    /// One [`Error::UnknownPermission`](crate::Error::UnknownPermission) per
    /// unregistered name, each carrying the closest registered name when there
    /// is one close enough.
    ///
    /// ```
    /// use moso_authz::{PermRef, PermissionRegistry};
    ///
    /// let registry = PermissionRegistry::from_entries(
    ///     vec![PermRef::new(0, "posts.publish", "Publish posts", "posts")],
    ///     7,
    /// );
    ///
    /// let problems = registry.check(&["posts.pubish"]).unwrap_err();
    /// assert_eq!(problems.len(), 1);
    /// assert!(problems[0].to_string().contains("did you mean `posts.publish`"));
    /// ```
    pub fn check<S: AsRef<str>>(&self, required: &[S]) -> Result<(), Vec<crate::Error>> {
        let problems: Vec<crate::Error> = required
            .iter()
            .map(AsRef::as_ref)
            .filter(|name| self.lookup(name).is_none())
            .map(|name| crate::Error::UnknownPermission {
                name: name.to_owned(),
                suggestion: self.suggest(name).map(ToOwned::to_owned),
            })
            .collect();
        if problems.is_empty() {
            Ok(())
        } else {
            Err(problems)
        }
    }

    /// Build a registry from descriptions rather than from a type.
    ///
    /// For a registry that came over the wire — the admin rendering another
    /// service's permissions — and for tests.
    ///
    /// ```
    /// use moso_authz::{PermRef, PermissionRegistry};
    ///
    /// let registry = PermissionRegistry::from_entries(
    ///     vec![PermRef::new(0, "posts.read", "View posts", "posts")],
    ///     1,
    /// );
    /// assert_eq!(registry.all().len(), 1);
    /// ```
    #[must_use]
    pub fn from_entries(entries: Vec<PermRef>, fingerprint: u64) -> Self {
        Self {
            entries,
            fingerprint,
        }
    }

    /// The fingerprint of the registry this describes.
    ///
    /// ```no_run
    /// # use moso_authz::PermissionRegistry;
    /// # fn f(r: &PermissionRegistry) { let _: u64 = r.fingerprint(); }
    /// ```
    #[must_use]
    pub fn fingerprint(&self) -> u64 {
        self.fingerprint
    }
}

/// Edit distance, the same measure Moso's macro diagnostics use.
///
/// Three rows rather than two: the row before last is what makes a
/// transposition — `pubish` for `publish` — cost one edit instead of two, which
/// is the single most common permission typo.
fn edit_distance(left: &str, right: &str) -> usize {
    if left == right {
        return 0;
    }
    let left: Vec<char> = left.chars().collect();
    let right: Vec<char> = right.chars().collect();
    if left.is_empty() {
        return right.len();
    }
    if right.is_empty() {
        return left.len();
    }

    let mut before_last = vec![0usize; right.len() + 1];
    let mut previous: Vec<usize> = (0..=right.len()).collect();
    let mut current = vec![0usize; right.len() + 1];

    for (row, left_char) in left.iter().copied().enumerate() {
        current[0] = row + 1;
        for (column, right_char) in right.iter().copied().enumerate() {
            let cost = usize::from(left_char != right_char);
            let mut best = (previous[column] + cost)
                .min(current[column] + 1)
                .min(previous[column + 1] + 1);
            if row > 0
                && column > 0
                && left_char == right[column - 1]
                && left[row - 1] == right_char
            {
                best = best.min(before_last[column - 1] + 1);
            }
            current[column + 1] = best;
        }
        core::mem::swap(&mut before_last, &mut previous);
        core::mem::swap(&mut previous, &mut current);
    }

    previous[right.len()]
}

/// Compute a registry fingerprint from permission names, in order.
///
/// A `const fn` so `permissions!` can emit
/// `const FINGERPRINT: u64 = fingerprint_of(&["posts.read", …]);` and the check
/// costs nothing at runtime. FNV-1a: not cryptographic, and it does not need to
/// be — this catches a mismatched build, not an attacker.
///
/// ```
/// use moso_authz::perm::fingerprint_of;
///
/// const A: u64 = fingerprint_of(&["posts.read"]);
/// const B: u64 = fingerprint_of(&["posts.read", "posts.write"]);
/// assert_ne!(A, B);
/// ```
#[must_use]
pub const fn fingerprint_of(names: &[&str]) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut i = 0;
    while i < names.len() {
        let bytes = names[i].as_bytes();
        let mut j = 0;
        while j < bytes.len() {
            hash ^= bytes[j] as u64;
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
            j += 1;
        }
        hash ^= 0xff;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        i += 1;
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixture::Perm;

    #[test]
    fn a_permission_is_in_the_set_it_was_put_in() {
        let set = PermSet::of([Perm::PostsRead, Perm::AdminAccess]);

        assert!(set.has(Perm::PostsRead));
        assert!(set.has(Perm::AdminAccess));
        assert!(!set.has(Perm::PostsPublish));
        assert_eq!(set.len(), 2);
    }

    #[test]
    fn removing_a_permission_leaves_the_others_alone() {
        let set = PermSet::of([Perm::PostsRead, Perm::PostsPublish]).without(Perm::PostsRead);

        assert!(!set.has(Perm::PostsRead));
        assert!(set.has(Perm::PostsPublish));
    }

    #[test]
    fn the_empty_set_holds_nothing_and_the_full_set_holds_everything() {
        let none: PermSet<Perm> = PermSet::empty();
        let all: PermSet<Perm> = PermSet::all();

        assert!(none.is_empty());
        assert_eq!(none.len(), 0);
        assert_eq!(all.len(), Perm::ALL.len());
        for permission in Perm::ALL.iter().copied() {
            assert!(all.has(permission), "{permission:?} should be in `all()`");
            assert!(!none.has(permission));
        }
    }

    #[test]
    fn has_all_and_has_any_read_the_way_requires_needs_them() {
        let held = PermSet::of([Perm::PostsRead, Perm::PostsUpdate]);

        assert!(held.has_all(PermSet::of([Perm::PostsRead])));
        assert!(held.has_all(PermSet::of([Perm::PostsRead, Perm::PostsUpdate])));
        assert!(!held.has_all(PermSet::of([Perm::PostsRead, Perm::AdminAccess])));

        assert!(held.has_any(PermSet::of([Perm::PostsRead, Perm::AdminAccess])));
        assert!(!held.has_any(PermSet::of([Perm::AdminAccess])));

        // The empty requirement is satisfied by everybody under `all`.
        assert!(held.has_all(PermSet::empty()));
        assert!(!held.has_any(PermSet::empty()));
    }

    #[test]
    fn the_set_operations_are_the_set_operations() {
        let left = PermSet::of([Perm::PostsRead, Perm::PostsUpdate]);
        let right = PermSet::of([Perm::PostsUpdate, Perm::AdminAccess]);

        assert_eq!(
            left.union(right),
            PermSet::of([Perm::PostsRead, Perm::PostsUpdate, Perm::AdminAccess]),
        );
        assert_eq!(left.intersection(right), PermSet::of([Perm::PostsUpdate]));
        assert_eq!(left.difference(right), PermSet::of([Perm::PostsRead]));
    }

    /// The API-key rule from `docs/03-batteries/31-authorization.md`: a key's
    /// scopes intersect the owner's permissions and can never add to them.
    #[test]
    fn an_intersection_can_never_grant_more_than_either_side_held() {
        let user = PermSet::of([Perm::PostsRead, Perm::PostsUpdate]);
        let key = PermSet::of([Perm::PostsUpdate, Perm::AdminAccess]);

        let effective = user.intersection(key);

        assert!(
            !effective.has(Perm::AdminAccess),
            "the key added a capability"
        );
        assert!(user.has_all(effective));
        assert!(key.has_all(effective));
    }

    #[test]
    fn iteration_is_in_registry_order() {
        let set = PermSet::of([Perm::AdminAccess, Perm::PostsRead, Perm::PostsUpdate]);

        assert_eq!(
            set.names(),
            ["posts.read", "posts.update", "admin.access"],
            "declaration order, not insertion order",
        );
    }

    #[test]
    fn names_round_trip_through_parse_all_and_report_the_misses() {
        let set = PermSet::of([Perm::PostsRead, Perm::AdminAccess]);
        let (parsed, unknown) = PermSet::<Perm>::parse_all(&set.names());

        assert_eq!(parsed, set);
        assert_eq!(unknown, 0);
    }

    /// A permission removed in a deploy must not stop every stored API key
    /// from working, so an unknown name is counted rather than fatal.
    #[test]
    fn an_unregistered_name_is_ignored_and_counted() {
        let (set, unknown) =
            PermSet::<Perm>::parse_all(&["posts.read", "posts.teleport", "admin.access"]);

        assert_eq!(set, PermSet::of([Perm::PostsRead, Perm::AdminAccess]));
        assert_eq!(unknown, 1);
    }

    #[test]
    fn bits_round_trip_within_one_registry() {
        let set = PermSet::of([Perm::PostsRead, Perm::AdminAccess]);
        let bits = set.to_bits();

        assert_eq!(bits.fingerprint(), Perm::FINGERPRINT);
        assert_eq!(
            PermSet::<Perm>::from_bits(bits).expect("same registry"),
            set
        );
    }

    /// The one way erased bits can go wrong: they came from a different
    /// registry, where every bit means something else.
    #[test]
    fn bits_from_another_registry_are_refused_rather_than_reinterpreted() {
        let foreign = PermBits::new([0b1111, 0, 0, 0], Perm::FINGERPRINT ^ 1);

        let error = PermSet::<Perm>::from_bits(foreign).expect_err("a different registry");

        assert!(matches!(error, crate::Error::UnknownPermission { .. }));
        assert!(error.to_string().contains("bits from registry"));
    }

    #[test]
    fn erased_bits_answer_the_same_questions_as_the_typed_set() {
        let held = PermSet::of([Perm::PostsRead, Perm::PostsUpdate]).to_bits();
        let wanted = PermSet::of([Perm::PostsRead]).to_bits();
        let unheld = PermSet::of([Perm::AdminAccess]).to_bits();

        assert!(held.has_all(wanted));
        assert!(!held.has_all(unheld));
        assert!(held.has_any(wanted));
        assert!(!held.has_any(unheld));
        assert_eq!(held.len(), 2);
        assert!(!held.is_empty());
        assert_eq!(
            held.indices().collect::<Vec<_>>(),
            vec![Perm::PostsRead.index(), Perm::PostsUpdate.index()],
        );
    }

    #[test]
    fn an_index_past_the_cap_is_not_set_rather_than_a_panic() {
        assert_eq!(position(MAX_PERMISSIONS as u16), None);
        assert!(!PermBits::new([u64::MAX; PERM_WORDS], 0).has_index(MAX_PERMISSIONS as u16));
    }

    /// A bitset in a log line is unreadable, and the point of a typed registry
    /// is that the names exist.
    #[test]
    fn debug_prints_names_and_not_bit_patterns() {
        let rendered = format!("{:?}", PermSet::of([Perm::PostsRead, Perm::AdminAccess]));

        assert_eq!(rendered, "PermSet{posts.read, admin.access}");
    }

    #[test]
    fn a_set_collected_from_an_iterator_is_the_same_set() {
        let collected: PermSet<Perm> = [Perm::PostsRead, Perm::AdminAccess].into_iter().collect();

        assert_eq!(collected, PermSet::of([Perm::PostsRead, Perm::AdminAccess]));
    }

    #[test]
    fn const_construction_agrees_with_the_runtime_one() {
        const VIEWER: PermSet<Perm> = PermSet::empty()
            .with_index(Perm::PostsRead as u16)
            .with_index(Perm::UsersRead as u16);

        assert_eq!(VIEWER, PermSet::of([Perm::PostsRead, Perm::UsersRead]));
        assert_eq!(PermSet::<Perm>::from_words(VIEWER.words()), VIEWER);
    }

    // ── the registry ──────────────────────────────────────────────────────

    #[test]
    fn the_registry_enumerates_the_whole_set_in_order() {
        let registry = PermissionRegistry::of::<Perm>();

        assert_eq!(registry.all().len(), Perm::ALL.len());
        assert_eq!(registry.all()[0].name(), "posts.read");
        assert_eq!(registry.all()[0].description(), "View posts");
        assert_eq!(registry.all()[0].index(), 0);
        assert_eq!(registry.fingerprint(), Perm::FINGERPRINT);
    }

    #[test]
    fn groups_are_deduplicated_in_first_seen_order() {
        let registry = PermissionRegistry::of::<Perm>();

        assert_eq!(registry.groups(), ["posts", "users", "admin"]);
        assert_eq!(registry.in_group("admin").len(), 2);
        assert!(registry.in_group("nothing").is_empty());
    }

    #[test]
    fn a_typo_gets_the_permission_it_was_meant_to_be() {
        let registry = PermissionRegistry::of::<Perm>();

        assert_eq!(registry.suggest("posts.pubish"), Some("posts.publish"));
        assert_eq!(registry.suggest("admin.acess"), Some("admin.access"));
        assert_eq!(registry.suggest("xyzzy"), None);
    }

    /// Acceptance criterion 1: an unknown permission is an error naming the
    /// closest real one, not a silent `false`.
    #[test]
    fn the_registry_check_reports_every_unknown_name_with_a_suggestion() {
        let registry = PermissionRegistry::of::<Perm>();

        assert!(registry.check(&["posts.read", "admin.access"]).is_ok());

        let problems = registry
            .check(&["posts.pubish", "posts.read", "nowhere.near"])
            .expect_err("two of the three are unknown");

        assert_eq!(problems.len(), 2);
        assert!(
            problems[0]
                .to_string()
                .contains("did you mean `posts.publish`"),
            "{}",
            problems[0]
        );
        assert!(
            !problems[1].to_string().contains("did you mean"),
            "nothing is close to `nowhere.near`: {}",
            problems[1]
        );
    }

    #[test]
    fn lookup_finds_a_permission_by_wire_name() {
        let registry = PermissionRegistry::of::<Perm>();

        assert_eq!(
            registry
                .lookup("admin.settings")
                .map(|entry| entry.group().to_owned()),
            Some("admin".to_owned()),
        );
        assert!(registry.lookup("admin.setting").is_none());
    }

    #[test]
    fn a_registry_built_from_entries_answers_the_same_questions() {
        let registry = PermissionRegistry::from_entries(
            vec![PermRef::new(0, "posts.read", "View posts", "posts")],
            7,
        );

        assert_eq!(registry.fingerprint(), 7);
        assert_eq!(registry.groups(), ["posts"]);
        assert!(registry.lookup("posts.read").is_some());
    }

    // ── the fingerprint ───────────────────────────────────────────────────

    #[test]
    fn the_fingerprint_is_order_sensitive_and_boundary_sensitive() {
        assert_ne!(
            fingerprint_of(&["a", "b"]),
            fingerprint_of(&["b", "a"]),
            "order is bit order",
        );
        assert_ne!(
            fingerprint_of(&["ab", "c"]),
            fingerprint_of(&["a", "bc"]),
            "a separator is needed between names",
        );
        assert_eq!(fingerprint_of(&["a", "b"]), fingerprint_of(&["a", "b"]));
        assert_ne!(fingerprint_of(&[]), fingerprint_of(&[""]));
    }

    // ── edit distance ─────────────────────────────────────────────────────

    #[test]
    fn a_transposition_costs_one_edit() {
        assert_eq!(edit_distance("pubish", "publish"), 1);
        assert_eq!(edit_distance("psots", "posts"), 1);
        assert_eq!(edit_distance("", "abc"), 3);
        assert_eq!(edit_distance("abc", ""), 3);
        assert_eq!(edit_distance("same", "same"), 0);
    }

    // ── the performance claim ─────────────────────────────────────────────

    /// `docs/03-batteries/31-authorization.md`: a `PermSet` check is a bitwise
    /// AND, about a nanosecond, and the framework's overhead per authorization
    /// check is under a microsecond. This measures the check itself; the
    /// end-to-end figure is in `tests/overhead.rs`.
    ///
    /// The threshold is a thousand times the claim, so the test says "this is
    /// not accidentally a hash lookup" rather than "this machine is fast".
    #[test]
    fn a_permission_check_is_a_bitwise_and() {
        let held = PermSet::of([Perm::PostsRead, Perm::PostsUpdate, Perm::AdminAccess]);
        let rounds = 2_000_000;

        let started = std::time::Instant::now();
        let mut hits = 0_u64;
        for round in 0..rounds {
            let wanted = Perm::ALL[round % Perm::ALL.len()];
            hits += u64::from(held.has(wanted));
        }
        let each = started.elapsed() / rounds as u32;

        assert!(hits > 0, "the loop was optimised away");
        assert!(
            each < std::time::Duration::from_micros(1),
            "a permission check took {each:?}, which is not a bitwise AND",
        );
    }
}
