//! Roles, role sets, and the scope a role is held in.
//!
//! # What `roles!` generates
//!
//! ```text
//! // written
//! moso::roles! {
//!     Viewer = [posts.read, users.read],
//!     Editor = Viewer + [posts.create, posts.update],
//!     Admin  = Editor + [posts.publish, admin.access],
//! }
//!
//! // generated
//! #[repr(u8)]
//! #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
//! pub enum Role { Viewer, Editor, Admin }
//!
//! impl Role {
//!     pub const ALL: &'static [Role] = &[Role::Viewer, Role::Editor, Role::Admin];
//!     /// Resolved at compile time — inheritance is flattened by the macro.
//!     pub const fn permissions(self) -> PermSet<Perm> { /* … */ }
//!     pub const fn as_str(self) -> &'static str { /* "editor" */ }
//! }
//!
//! impl ::moso::__private::Role for Role { type Perm = Perm; /* … */ }
//! ```
//!
//! Inheritance (`Editor = Viewer + [..]`) is resolved **by the macro**, so a
//! static role's permissions are a `const PermSet` and resolving them at runtime
//! costs nothing. A cycle in the inheritance graph is a macro error naming both
//! roles.
//!
//! # Static and dynamic roles compose
//!
//! Static roles cover most applications. Multi-tenant SaaS where customers
//! define their own roles needs [`RoleSource`], which returns a `RoleSet` and an
//! extra `PermSet` from a table. The two are unioned; the docs are explicit
//! that a dynamic role can only ever grant permissions the registry already
//! declares, because there is no bit for anything else.

use core::marker::PhantomData;

use chrono::{DateTime, Utc};
use moso_core::BoxFuture;
use serde::{Deserialize, Serialize};

use crate::{ActorId, PermSet, Permission};

/// The largest role registry `roles!` will accept.
///
/// Sixty-four is one word, which keeps [`RoleSet`] eight bytes and `Copy`.
/// Static roles are a small fixed vocabulary — customer-defined roles are
/// [`RoleSource`]'s job and are not bounded by this.
///
/// ```
/// assert_eq!(moso_authz::MAX_ROLES, 64);
/// ```
pub const MAX_ROLES: usize = 64;

/// A role registry: what `roles!` implements on the generated enum.
///
/// ```no_run
/// use moso_authz::{PermSet, Role};
///
/// fn grants<R: Role>(role: R) -> PermSet<R::Perm> {
///     role.permissions()
/// }
/// ```
///
/// # The name
///
/// The generated enum in the application's crate is also called `Role`, which
/// is the right name at a call site. Generated code writes
/// `impl ::moso::__private::Role for Role`, so the two never collide; hand-
/// written code that needs the trait imports it explicitly. It is deliberately
/// **not** in [`crate::prelude`] for that reason.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a role set generated by `roles!`",
    label = "not a role",
    note = "the role enum is generated — write `moso::roles! {{ Editor = [posts.update] }}` next \
            to your `permissions!` and use the `Role` it produces",
    note = "help: a hand-written role enum must implement `Role`, which needs `Perm`, `ALL`, \
            `index`, `as_str`, `description`, `permissions` and `parse`",
    note = "help: for customer-defined roles stored in a table, implement `RoleSource` instead \
            — it composes with the static ones"
)]
pub trait Role: Copy + Eq + core::hash::Hash + Send + Sync + 'static {
    /// The permission registry this role's permissions come from.
    type Perm: Permission;

    /// Every role, in declaration order. Index `i` is `ALL[i]`.
    const ALL: &'static [Self];

    /// This role's index, which is its bit in a [`RoleSet`].
    fn index(self) -> u8;

    /// The role at `index`, or `None` when nothing is registered there.
    fn from_index(index: u8) -> Option<Self>;

    /// The wire name, e.g. `"editor"`. Lowercased from the variant.
    fn as_str(self) -> &'static str;

    /// The human description, for the admin's role editor.
    fn description(self) -> &'static str;

    /// The permissions the role grants, with inheritance already flattened.
    ///
    /// The generated enum also has an inherent `const fn permissions`; this
    /// method delegates to it, so resolving a static role is a copy of four
    /// words and no allocation.
    fn permissions(self) -> PermSet<Self::Perm>;

    /// Parse a wire name back into a role, for a database round trip.
    fn parse(name: &str) -> Option<Self>;
}

/// A compact set of roles. One `u64`, `Copy`, eight bytes.
///
/// ```no_run
/// use moso_authz::{PermSet, Role, RoleSet};
///
/// fn granted<R: Role>(roles: RoleSet<R>) -> PermSet<R::Perm> {
///     roles.permissions()
/// }
/// ```
pub struct RoleSet<R: Role> {
    /// Bit `i` is `R::ALL[i]`.
    bits: u64,
    /// The role type, which holds no data.
    marker: PhantomData<fn() -> R>,
}

impl<R: Role> RoleSet<R> {
    /// The empty set.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>() { let _: RoleSet<R> = RoleSet::empty(); }
    /// ```
    #[must_use]
    pub const fn empty() -> Self {
        Self {
            bits: 0,
            marker: PhantomData,
        }
    }

    /// A set holding exactly the given roles.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(a: R) { let _ = RoleSet::of([a]); }
    /// ```
    #[must_use]
    pub fn of(roles: impl IntoIterator<Item = R>) -> Self {
        roles
            .into_iter()
            .fold(Self::empty(), |set, role| set.with(role))
    }

    /// A set from raw bits, for a cached or stored resolution.
    ///
    /// `const`, so a generated constant can name one.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>() { let _: RoleSet<R> = RoleSet::from_bits(0b101); }
    /// ```
    #[must_use]
    pub const fn from_bits(bits: u64) -> Self {
        Self {
            bits,
            marker: PhantomData,
        }
    }

    /// The raw bits.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: u64 = s.bits(); }
    /// ```
    #[must_use]
    pub const fn bits(self) -> u64 {
        self.bits
    }

    /// Add a role, returning the new set.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(r: R) { let _ = RoleSet::empty().with(r); }
    /// ```
    #[must_use]
    pub fn with(mut self, role: R) -> Self {
        if (role.index() as usize) < MAX_ROLES {
            self.bits |= 1u64 << role.index();
        }
        self
    }

    /// Remove a role, returning the new set.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>, r: R) { let _ = s.without(r); }
    /// ```
    #[must_use]
    pub fn without(mut self, role: R) -> Self {
        if (role.index() as usize) < MAX_ROLES {
            self.bits &= !(1u64 << role.index());
        }
        self
    }

    /// Whether the set holds `role`.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>, r: R) { let _: bool = s.has(r); }
    /// ```
    #[must_use]
    pub fn has(self, role: R) -> bool {
        (role.index() as usize) < MAX_ROLES && self.bits & (1u64 << role.index()) != 0
    }

    /// Everything in either set.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(a: RoleSet<R>, b: RoleSet<R>) { let _ = a.union(b); }
    /// ```
    #[must_use]
    pub fn union(mut self, other: Self) -> Self {
        self.bits |= other.bits;
        self
    }

    /// The union of every held role's permissions.
    ///
    /// The only place static role resolution happens, and it is a fold over at
    /// most 64 `const` sets.
    ///
    /// ```no_run
    /// # use moso_authz::{PermSet, Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: PermSet<R::Perm> = s.permissions(); }
    /// ```
    #[must_use]
    pub fn permissions(self) -> PermSet<R::Perm> {
        self.iter()
            .map(Role::permissions)
            .fold(PermSet::empty(), PermSet::union)
    }

    /// How many roles the set holds.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: usize = s.len(); }
    /// ```
    #[must_use]
    pub fn len(self) -> usize {
        self.bits.count_ones() as usize
    }

    /// Whether the set is empty.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: bool = s.is_empty(); }
    /// ```
    #[must_use]
    pub fn is_empty(self) -> bool {
        self.bits == 0
    }

    /// The roles in the set, in registry order.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: Vec<R> = s.iter().collect(); }
    /// ```
    pub fn iter(self) -> impl Iterator<Item = R> {
        R::ALL.iter().copied().filter(move |role| self.has(*role))
    }

    /// The wire names, in registry order.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(s: RoleSet<R>) { let _: Vec<&'static str> = s.names(); }
    /// ```
    #[must_use]
    pub fn names(self) -> Vec<&'static str> {
        self.iter().map(Role::as_str).collect()
    }

    /// Parse a set from wire names, ignoring anything unregistered.
    ///
    /// The count of ignored names is returned so a caller can log a role that
    /// a deploy removed while assignments still referenced it.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleSet};
    /// # fn f<R: Role>(n: &[String]) { let _: (RoleSet<R>, usize) = RoleSet::parse_all(n); }
    /// ```
    #[must_use]
    pub fn parse_all<S: AsRef<str>>(names: &[S]) -> (Self, usize) {
        let mut set = Self::empty();
        let mut unknown = 0;
        for name in names {
            match R::parse(name.as_ref()) {
                Some(role) => set = set.with(role),
                None => unknown += 1,
            }
        }
        (set, unknown)
    }
}

impl<R: Role> Clone for RoleSet<R> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<R: Role> Copy for RoleSet<R> {}

impl<R: Role> Default for RoleSet<R> {
    fn default() -> Self {
        Self::empty()
    }
}

impl<R: Role> PartialEq for RoleSet<R> {
    fn eq(&self, other: &Self) -> bool {
        self.bits == other.bits
    }
}

impl<R: Role> Eq for RoleSet<R> {}

impl<R: Role> core::hash::Hash for RoleSet<R> {
    fn hash<H: core::hash::Hasher>(&self, state: &mut H) {
        self.bits.hash(state);
    }
}

impl<R: Role> core::fmt::Debug for RoleSet<R> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("RoleSet{")?;
        for (position, name) in self.names().into_iter().enumerate() {
            if position > 0 {
                f.write_str(", ")?;
            }
            f.write_str(name)?;
        }
        f.write_str("}")
    }
}

/// Where a role is held.
///
/// The model almost every business-to-business application eventually needs:
/// somebody is an admin *of one organisation* and a viewer *of another*. Getting
/// this wrong later means rewriting every authorization call site, so it is in
/// the model from the start even for applications that only ever use
/// [`Scope::Global`].
///
/// ```
/// use moso_authz::{Scope, ScopeId};
///
/// let global = Scope::Global;
/// assert!(global.is_global());
///
/// let org = Scope::Org(ScopeId::new("acme"));
/// assert!(!org.is_global());
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum Scope {
    /// Everywhere in the application.
    Global,
    /// One organisation, tenant or workspace.
    Org(ScopeId),
    /// One project inside an organisation.
    Project(ScopeId),
    /// Anything else the application models.
    Custom {
        /// What kind of thing the scope names, e.g. `"team"`.
        kind: String,
        /// Which one.
        id: ScopeId,
    },
}

impl Scope {
    /// Whether this is [`Scope::Global`].
    ///
    /// ```
    /// use moso_authz::Scope;
    ///
    /// assert!(Scope::Global.is_global());
    /// ```
    #[must_use]
    pub fn is_global(&self) -> bool {
        matches!(self, Self::Global)
    }

    /// The identifier, for every scope but [`Scope::Global`].
    ///
    /// ```
    /// use moso_authz::Scope;
    ///
    /// assert!(Scope::Global.id().is_none());
    /// ```
    #[must_use]
    pub fn id(&self) -> Option<&ScopeId> {
        match self {
            Self::Global => None,
            Self::Org(id) | Self::Project(id) | Self::Custom { id, .. } => Some(id),
        }
    }

    /// Whether a role held in this scope applies to a request in `other`.
    ///
    /// [`Scope::Global`] applies everywhere; everything else applies only to
    /// itself. Deliberately **not** hierarchical: "org admin implies project
    /// admin" is an application's decision, and building it in here would make
    /// every application that disagrees insecure by default.
    ///
    /// ```no_run
    /// use moso_authz::{Scope, ScopeId};
    ///
    /// assert!(Scope::Global.covers(&Scope::Org(ScopeId::new("acme"))));
    /// assert!(!Scope::Org(ScopeId::new("acme")).covers(&Scope::Global));
    /// ```
    #[must_use]
    pub fn covers(&self, other: &Self) -> bool {
        self.is_global() || self == other
    }

    /// The scope as one string, for a cache key or an audit record.
    ///
    /// ```no_run
    /// use moso_authz::{Scope, ScopeId};
    ///
    /// assert_eq!(Scope::Global.as_key(), "global");
    /// assert_eq!(Scope::Org(ScopeId::new("acme")).as_key(), "org:acme");
    /// ```
    #[must_use]
    pub fn as_key(&self) -> String {
        match self {
            Self::Global => "global".to_owned(),
            Self::Org(id) => format!("org:{id}"),
            Self::Project(id) => format!("project:{id}"),
            Self::Custom { kind, id } => format!("{kind}:{id}"),
        }
    }
}

/// The identifier of a scope.
///
/// A string, because tenants are identified by a UUID in one application, a
/// slug in another and a bigint in a third, and a scope that only accepted one
/// of those would be wrong for two thirds of its users. `From` impls cover all
/// three so no call site has to write the conversion.
///
/// ```
/// use moso_authz::ScopeId;
///
/// let from_slug = ScopeId::new("acme");
/// let from_int = ScopeId::from(42_i64);
/// assert_eq!(from_slug.as_str(), "acme");
/// assert_eq!(from_int.as_str(), "42");
/// ```
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ScopeId(String);

impl ScopeId {
    /// Wrap an identifier.
    ///
    /// ```
    /// use moso_authz::ScopeId;
    ///
    /// assert_eq!(ScopeId::new("acme").as_str(), "acme");
    /// ```
    #[must_use]
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    /// The identifier.
    ///
    /// ```
    /// use moso_authz::ScopeId;
    ///
    /// assert_eq!(ScopeId::new("x").as_str(), "x");
    /// ```
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<i64> for ScopeId {
    fn from(value: i64) -> Self {
        Self(value.to_string())
    }
}

impl<E: moso_schema::IdMarker> From<moso_schema::Id<E>> for ScopeId {
    fn from(value: moso_schema::Id<E>) -> Self {
        Self(value.to_string())
    }
}

impl core::fmt::Display for ScopeId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}

/// One row of "this subject holds this role here".
///
/// ```no_run
/// use moso_authz::{Role, RoleAssignment};
///
/// # fn f<R: Role>(a: &RoleAssignment<R>) {
/// let _ = &a.scope;
/// # }
/// ```
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(bound = "")]
#[non_exhaustive]
pub struct RoleAssignment<R: Role> {
    /// Who holds it.
    pub subject: ActorId,
    /// Which role, by wire name — so a removed role does not break
    /// deserialisation of stored rows.
    pub role: String,
    /// Where they hold it.
    pub scope: Scope,
    /// When it was granted.
    pub granted_at: DateTime<Utc>,
    /// When it stops applying, when it does.
    pub expires_at: Option<DateTime<Utc>>,
    /// The role type, which holds no data.
    #[serde(skip)]
    pub marker: PhantomData<fn() -> R>,
}

impl<R: Role> RoleAssignment<R> {
    /// Grant `role` to `subject` in `scope`, as of now.
    ///
    /// ```no_run
    /// # use moso_authz::{ActorId, Role, RoleAssignment, Scope};
    /// # fn f<R: Role>(id: ActorId, role: R) {
    /// let _ = RoleAssignment::new(id, role, Scope::Global);
    /// # }
    /// ```
    #[must_use]
    pub fn new(subject: ActorId, role: R, scope: Scope) -> Self {
        Self {
            subject,
            role: role.as_str().to_owned(),
            scope,
            granted_at: Utc::now(),
            expires_at: None,
            marker: PhantomData,
        }
    }

    /// The same assignment, expiring at `at`.
    ///
    /// ```no_run
    /// # use chrono::Utc;
    /// # use moso_authz::{Role, RoleAssignment};
    /// # fn f<R: Role>(a: RoleAssignment<R>) { let _ = a.expiring_at(Utc::now()); }
    /// ```
    #[must_use]
    pub fn expiring_at(mut self, at: DateTime<Utc>) -> Self {
        self.expires_at = Some(at);
        self
    }

    /// The role, when it is still registered.
    ///
    /// `None` for an assignment whose role a deploy removed — which is a
    /// condition worth logging rather than crashing on.
    ///
    /// ```no_run
    /// # use moso_authz::{Role, RoleAssignment};
    /// # fn f<R: Role>(a: &RoleAssignment<R>) { let _: Option<R> = a.resolve(); }
    /// ```
    #[must_use]
    pub fn resolve(&self) -> Option<R> {
        R::parse(&self.role)
    }

    /// Whether the assignment is in force at `now`.
    ///
    /// ```no_run
    /// # use chrono::Utc;
    /// # use moso_authz::{Role, RoleAssignment};
    /// # fn f<R: Role>(a: &RoleAssignment<R>) { let _: bool = a.is_active(Utc::now()); }
    /// ```
    #[must_use]
    pub fn is_active(&self, now: DateTime<Utc>) -> bool {
        self.granted_at <= now && self.expires_at.is_none_or(|expiry| expiry > now)
    }
}

/// Where customer-defined roles come from.
///
/// Static roles are a `const PermSet` and need no source. This is for the
/// multi-tenant case where a customer administrator builds their own roles in
/// the product, stored in a table.
///
/// Dyn-compatible, because which source an application uses is configuration.
///
/// ```no_run
/// use moso_authz::{ActorId, Role, RoleSource, Scope};
///
/// async fn resolve<R: Role>(source: &dyn RoleSource<R>, id: &ActorId)
///     -> moso_authz::Result<()>
/// {
///     let _ = source.roles_for(id, &Scope::Global).await?;
///     Ok(())
/// }
/// ```
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a role source",
    label = "not a role source",
    note = "a role source implements `roles_for` and `extra_permissions`, both returning what \
            the subject holds in one scope",
    note = "help: you only need one for customer-defined roles stored in a table; static roles \
            from `roles!` are resolved at compile time and need no source"
)]
pub trait RoleSource<R: Role>: Send + Sync + 'static {
    /// The static roles the subject holds in `scope`.
    ///
    /// # Errors
    ///
    /// [`Error::Unavailable`](crate::Error::Unavailable) when the store cannot
    /// be reached — which must become a 503, never an empty set.
    fn roles_for<'a>(
        &'a self,
        subject: &'a ActorId,
        scope: &'a Scope,
    ) -> BoxFuture<'a, crate::Result<RoleSet<R>>>;

    /// Permissions granted directly, outside any static role.
    ///
    /// This is where a customer-defined role's contents land: the source
    /// resolves the customer's own role definition into permissions the
    /// registry already declares.
    ///
    /// # Errors
    ///
    /// As [`roles_for`](RoleSource::roles_for).
    fn extra_permissions<'a>(
        &'a self,
        subject: &'a ActorId,
        scope: &'a Scope,
    ) -> BoxFuture<'a, crate::Result<PermSet<R::Perm>>> {
        let _ = (subject, scope);
        Box::pin(async { Ok(PermSet::empty()) })
    }

    /// Every assignment for a subject, across every scope. For the admin UI.
    ///
    /// # Errors
    ///
    /// As [`roles_for`](RoleSource::roles_for).
    fn assignments<'a>(
        &'a self,
        subject: &'a ActorId,
    ) -> BoxFuture<'a, crate::Result<Vec<RoleAssignment<R>>>> {
        let _ = subject;
        Box::pin(async { Ok(Vec::new()) })
    }
}

/// A [`RoleSource`] that holds its assignments in memory.
///
/// The shipped source for tests and for an application whose roles are static
/// but whose *assignments* are not — a fixture, a seeded development database,
/// a single-tenant deployment configured from a file.
///
/// ```
/// use moso_authz::{ActorId, MemoryRoleSource, Scope};
/// # use moso_authz::{PermSet, Permission, Role, RoleAssignment, perm::fingerprint_of};
/// # #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)] pub enum Perm { Read }
/// # impl Permission for Perm {
/// #     const ALL: &'static [Self] = &[Perm::Read];
/// #     const FINGERPRINT: u64 = fingerprint_of(&["posts.read"]);
/// #     fn index(self) -> u16 { 0 }
/// #     fn from_index(i: u16) -> Option<Self> { (i == 0).then_some(Perm::Read) }
/// #     fn as_str(self) -> &'static str { "posts.read" }
/// #     fn description(self) -> &'static str { "View posts" }
/// #     fn group(self) -> &'static str { "posts" }
/// #     fn parse(n: &str) -> Option<Self> { (n == "posts.read").then_some(Perm::Read) }
/// # }
/// # #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)] pub enum Viewer { Viewer }
/// # impl Role for Viewer {
/// #     type Perm = Perm;
/// #     const ALL: &'static [Self] = &[Viewer::Viewer];
/// #     fn index(self) -> u8 { 0 }
/// #     fn from_index(i: u8) -> Option<Self> { (i == 0).then_some(Viewer::Viewer) }
/// #     fn as_str(self) -> &'static str { "viewer" }
/// #     fn description(self) -> &'static str { "Read-only" }
/// #     fn permissions(self) -> PermSet<Perm> { PermSet::of([Perm::Read]) }
/// #     fn parse(n: &str) -> Option<Self> { (n == "viewer").then_some(Viewer::Viewer) }
/// # }
/// let source = MemoryRoleSource::<Viewer>::new()
///     .granting(RoleAssignment::new(ActorId::new("usr_1"), Viewer::Viewer, Scope::Global));
///
/// assert_eq!(source.len(), 1);
/// ```
pub struct MemoryRoleSource<R: Role> {
    /// Every assignment, in insertion order.
    assignments: std::sync::RwLock<Vec<RoleAssignment<R>>>,
    /// Permissions granted directly, per subject and scope key.
    extra: std::sync::RwLock<Vec<DirectGrant<R>>>,
}

/// One "this subject also holds these permissions here" row.
///
/// Named rather than written inline: `RwLock<Vec<(ActorId, Scope,
/// PermSet<R::Perm>)>>` is a type nobody should have to parse, and the name says
/// what the tuple means.
///
/// The scope is kept as a [`Scope`] and not as its cache key, so that
/// [`MemoryRoleSource::extra_permissions`] can answer with [`Scope::covers`] —
/// the same rule [`MemoryRoleSource::roles_for`] applies. A source whose two
/// halves match scopes differently is a source that grants a role in one scope
/// and its permissions in another.
type DirectGrant<R> = (ActorId, Scope, PermSet<<R as Role>::Perm>);

impl<R: Role> MemoryRoleSource<R> {
    /// An empty source.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role};
    /// # fn f<R: Role>() { let _ = MemoryRoleSource::<R>::new(); }
    /// ```
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Add an assignment, by value, for a builder chain.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role, RoleAssignment};
    /// # fn f<R: Role>(a: RoleAssignment<R>) { let _ = MemoryRoleSource::new().granting(a); }
    /// ```
    #[must_use]
    pub fn granting(self, assignment: RoleAssignment<R>) -> Self {
        self.grant(assignment);
        self
    }

    /// Add an assignment.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role, RoleAssignment};
    /// # fn f<R: Role>(s: &MemoryRoleSource<R>, a: RoleAssignment<R>) { s.grant(a); }
    /// ```
    pub fn grant(&self, assignment: RoleAssignment<R>) {
        write(&self.assignments).push(assignment);
    }

    /// Grant permissions directly, outside any static role — the shape a
    /// customer-defined role resolves into.
    ///
    /// ```no_run
    /// # use moso_authz::{ActorId, MemoryRoleSource, PermSet, Role, Scope};
    /// # fn f<R: Role>(s: &MemoryRoleSource<R>, p: PermSet<R::Perm>) {
    /// s.grant_permissions(ActorId::new("usr_1"), &Scope::Global, p);
    /// # }
    /// ```
    pub fn grant_permissions(
        &self,
        subject: ActorId,
        scope: &Scope,
        permissions: PermSet<R::Perm>,
    ) {
        write(&self.extra).push((subject, scope.clone(), permissions));
    }

    /// How many assignments are held.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role};
    /// # fn f<R: Role>(s: &MemoryRoleSource<R>) { let _: usize = s.len(); }
    /// ```
    #[must_use]
    pub fn len(&self) -> usize {
        read(&self.assignments).len()
    }

    /// Whether nothing is assigned.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role};
    /// # fn f<R: Role>(s: &MemoryRoleSource<R>) { let _: bool = s.is_empty(); }
    /// ```
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Forget every assignment and every direct grant.
    ///
    /// ```no_run
    /// # use moso_authz::{MemoryRoleSource, Role};
    /// # fn f<R: Role>(s: &MemoryRoleSource<R>) { s.clear(); }
    /// ```
    pub fn clear(&self) {
        write(&self.assignments).clear();
        write(&self.extra).clear();
    }
}

impl<R: Role> Default for MemoryRoleSource<R> {
    fn default() -> Self {
        Self {
            assignments: std::sync::RwLock::new(Vec::new()),
            extra: std::sync::RwLock::new(Vec::new()),
        }
    }
}

impl<R: Role> core::fmt::Debug for MemoryRoleSource<R> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("MemoryRoleSource")
            .field("assignments", &self.len())
            .finish_non_exhaustive()
    }
}

impl<R: Role> RoleSource<R> for MemoryRoleSource<R> {
    fn roles_for<'a>(
        &'a self,
        subject: &'a ActorId,
        scope: &'a Scope,
    ) -> BoxFuture<'a, crate::Result<RoleSet<R>>> {
        Box::pin(async move {
            let now = Utc::now();
            let mut set = RoleSet::empty();
            for assignment in read(&self.assignments).iter() {
                if &assignment.subject == subject
                    && assignment.scope.covers(scope)
                    && assignment.is_active(now)
                    && let Some(role) = assignment.resolve()
                {
                    set = set.with(role);
                }
            }
            Ok(set)
        })
    }

    fn extra_permissions<'a>(
        &'a self,
        subject: &'a ActorId,
        scope: &'a Scope,
    ) -> BoxFuture<'a, crate::Result<PermSet<R::Perm>>> {
        Box::pin(async move {
            let mut set = PermSet::empty();
            for (held_by, held_in, permissions) in read(&self.extra).iter() {
                // `covers`, exactly as `roles_for` does it: a source that
                // matched scopes one way for roles and another way for direct
                // grants would grant a customer-defined role's permissions in
                // scopes the role itself does not reach.
                if held_by == subject && held_in.covers(scope) {
                    set = set.union(*permissions);
                }
            }
            Ok(set)
        })
    }

    fn assignments<'a>(
        &'a self,
        subject: &'a ActorId,
    ) -> BoxFuture<'a, crate::Result<Vec<RoleAssignment<R>>>> {
        Box::pin(async move {
            Ok(read(&self.assignments)
                .iter()
                .filter(|assignment| &assignment.subject == subject)
                .cloned()
                .collect())
        })
    }
}

/// Read a lock, recovering from poisoning.
///
/// Nothing inside a critical section here can panic — it compares strings and
/// copies bitsets — so a poisoned lock means a panic elsewhere in the process.
/// Refusing to authorise over that would turn an unrelated bug into a
/// site-wide outage, and the vector behind the lock cannot be half-updated.
fn read<T>(lock: &std::sync::RwLock<T>) -> std::sync::RwLockReadGuard<'_, T> {
    lock.read()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

/// [`read`]'s mutable half.
fn write<T>(lock: &std::sync::RwLock<T>) -> std::sync::RwLockWriteGuard<'_, T> {
    lock.write()
        .unwrap_or_else(std::sync::PoisonError::into_inner)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixture::{Perm, Role};

    #[test]
    fn a_role_set_holds_what_it_was_given() {
        let held = RoleSet::of([Role::Editor, Role::Admin]);

        assert!(held.has(Role::Editor));
        assert!(!held.has(Role::Viewer));
        assert_eq!(held.len(), 2);
        assert_eq!(held.names(), ["editor", "admin"]);
        assert!(!held.is_empty());
    }

    #[test]
    fn removing_and_unioning_behave_like_a_set() {
        let held = RoleSet::of([Role::Viewer, Role::Editor]).without(Role::Viewer);

        assert_eq!(held, RoleSet::of([Role::Editor]));
        assert_eq!(
            held.union(RoleSet::of([Role::Admin])),
            RoleSet::of([Role::Editor, Role::Admin]),
        );
    }

    /// The inheritance in `docs/03-batteries/31-authorization.md`:
    /// `Editor = Viewer + [..]`, `Admin = Editor + [..]`, `Owner = Admin + [..]`.
    #[test]
    fn inheritance_is_already_flattened_when_a_role_is_resolved() {
        assert!(Role::Editor.permissions().has(Perm::PostsRead));
        assert!(Role::Admin.permissions().has(Perm::PostsRead));
        assert!(Role::Owner.permissions().has(Perm::PostsRead));

        assert!(!Role::Viewer.permissions().has(Perm::PostsPublish));
        assert!(Role::Admin.permissions().has(Perm::PostsPublish));

        assert!(!Role::Admin.permissions().has(Perm::AdminSettings));
        assert!(Role::Owner.permissions().has(Perm::AdminSettings));
    }

    #[test]
    fn a_role_set_grants_the_union_of_its_roles() {
        let held = RoleSet::of([Role::Viewer, Role::Editor]);

        assert_eq!(held.permissions(), Role::Editor.permissions());
        assert_eq!(
            RoleSet::<Role>::empty().permissions(),
            PermSet::<Perm>::empty(),
        );
    }

    #[test]
    fn role_names_round_trip_and_an_unknown_one_is_counted() {
        let (parsed, unknown) = RoleSet::<Role>::parse_all(&["editor", "sorcerer", "admin"]);

        assert_eq!(parsed, RoleSet::of([Role::Editor, Role::Admin]));
        assert_eq!(unknown, 1);
    }

    #[test]
    fn debug_prints_role_names() {
        assert_eq!(
            format!("{:?}", RoleSet::of([Role::Viewer, Role::Owner])),
            "RoleSet{viewer, owner}",
        );
    }

    #[test]
    fn raw_bits_round_trip() {
        let held = RoleSet::of([Role::Viewer, Role::Admin]);
        assert_eq!(RoleSet::<Role>::from_bits(held.bits()), held);
    }

    // ── scopes ────────────────────────────────────────────────────────────

    /// Deliberately **not** hierarchical: "org admin implies project admin" is
    /// an application's decision, and building it in here would make every
    /// application that disagrees insecure by default.
    #[test]
    fn global_covers_everything_and_nothing_else_does() {
        let acme = Scope::Org(ScopeId::new("acme"));
        let project = Scope::Project(ScopeId::new("acme"));

        assert!(Scope::Global.covers(&acme));
        assert!(Scope::Global.covers(&Scope::Global));
        assert!(acme.covers(&acme));
        assert!(!acme.covers(&Scope::Global));
        assert!(!acme.covers(&project), "an org does not imply its projects");
    }

    #[test]
    fn a_scope_renders_as_a_stable_cache_key() {
        assert_eq!(Scope::Global.as_key(), "global");
        assert_eq!(Scope::Org(ScopeId::new("acme")).as_key(), "org:acme");
        assert_eq!(
            Scope::Project(ScopeId::new("apollo")).as_key(),
            "project:apollo",
        );
        assert_eq!(
            Scope::Custom {
                kind: "team".to_owned(),
                id: ScopeId::new("core"),
            }
            .as_key(),
            "team:core",
        );
    }

    #[test]
    fn a_scope_identifier_accepts_the_three_shapes_an_application_uses() {
        assert_eq!(ScopeId::new("acme").as_str(), "acme");
        assert_eq!(ScopeId::from(42_i64).as_str(), "42");
        assert_eq!(ScopeId::new("x").to_string(), "x");
    }

    // ── assignments ───────────────────────────────────────────────────────

    #[test]
    fn an_assignment_is_active_until_it_expires() {
        let now = Utc::now();
        let assignment = RoleAssignment::new(ActorId::new("usr_1"), Role::Editor, Scope::Global);

        assert!(assignment.is_active(now + chrono::Duration::seconds(1)));
        assert_eq!(assignment.resolve(), Some(Role::Editor));

        let expired = assignment.expiring_at(now - chrono::Duration::seconds(1));
        assert!(!expired.is_active(now));
    }

    /// A deploy that removes a role must not make every stored assignment
    /// undeserialisable — the row keeps the wire name and `resolve` says `None`.
    #[test]
    fn an_assignment_to_a_removed_role_resolves_to_nothing() {
        let mut assignment =
            RoleAssignment::new(ActorId::new("usr_1"), Role::Editor, Scope::Global);
        assignment.role = "sorcerer".to_owned();

        assert_eq!(assignment.resolve(), None);
    }

    // ── the memory source ─────────────────────────────────────────────────

    #[tokio::test]
    async fn the_memory_source_resolves_the_roles_held_in_a_scope() {
        let acme = Scope::Org(ScopeId::new("acme"));
        let source = MemoryRoleSource::<Role>::new()
            .granting(RoleAssignment::new(
                ActorId::new("usr_1"),
                Role::Viewer,
                Scope::Global,
            ))
            .granting(RoleAssignment::new(
                ActorId::new("usr_1"),
                Role::Admin,
                acme.clone(),
            ))
            .granting(RoleAssignment::new(
                ActorId::new("usr_2"),
                Role::Owner,
                Scope::Global,
            ));

        let alice = ActorId::new("usr_1");

        // Globally: only the global grant.
        assert_eq!(
            source
                .roles_for(&alice, &Scope::Global)
                .await
                .expect("roles"),
            RoleSet::of([Role::Viewer]),
        );
        // In `acme`: the global one applies here too, plus the scoped one.
        assert_eq!(
            source.roles_for(&alice, &acme).await.expect("roles"),
            RoleSet::of([Role::Viewer, Role::Admin]),
        );
        // In another org: only the global one.
        assert_eq!(
            source
                .roles_for(&alice, &Scope::Org(ScopeId::new("other")))
                .await
                .expect("roles"),
            RoleSet::of([Role::Viewer]),
        );
        assert_eq!(source.assignments(&alice).await.expect("list").len(), 2);
        assert_eq!(source.len(), 3);
    }

    #[tokio::test]
    async fn an_expired_assignment_is_not_resolved() {
        let source = MemoryRoleSource::<Role>::new().granting(
            RoleAssignment::new(ActorId::new("usr_1"), Role::Owner, Scope::Global)
                .expiring_at(Utc::now() - chrono::Duration::days(1)),
        );

        assert!(
            source
                .roles_for(&ActorId::new("usr_1"), &Scope::Global)
                .await
                .expect("roles")
                .is_empty(),
        );
    }

    /// A customer-defined role resolves into permissions the registry already
    /// declares — there is no bit for anything else.
    #[tokio::test]
    async fn direct_grants_compose_with_static_roles() {
        let source = MemoryRoleSource::<Role>::new();
        source.grant_permissions(
            ActorId::new("usr_1"),
            &Scope::Global,
            PermSet::of([Perm::AdminAccess]),
        );

        let extra = source
            .extra_permissions(&ActorId::new("usr_1"), &Scope::Global)
            .await
            .expect("permissions");

        assert_eq!(extra, PermSet::of([Perm::AdminAccess]));
        assert_eq!(
            Role::Viewer.permissions().union(extra).len(),
            Role::Viewer.permissions().len() + 1,
        );

        source.clear();
        assert!(source.is_empty());
    }

    /// Both halves of the source match scopes with [`Scope::covers`]. Matching
    /// by key string instead — which this used to do — agrees for `Global` and
    /// for an exact scope and disagrees the moment either side grows a rule,
    /// and a source that grants a role in one scope and its permissions in
    /// another is a source nobody can reason about.
    #[tokio::test]
    async fn direct_grants_and_roles_match_a_scope_the_same_way() {
        let acme = Scope::Org(ScopeId::new("acme"));
        let other = Scope::Org(ScopeId::new("other"));
        let alice = ActorId::new("usr_1");

        let source = MemoryRoleSource::<Role>::new()
            .granting(RoleAssignment::new(
                alice.clone(),
                Role::Viewer,
                Scope::Global,
            ))
            .granting(RoleAssignment::new(
                alice.clone(),
                Role::Admin,
                acme.clone(),
            ));
        source.grant_permissions(
            alice.clone(),
            &Scope::Global,
            PermSet::of([Perm::AdminAccess]),
        );
        source.grant_permissions(alice.clone(), &acme, PermSet::of([Perm::AdminSettings]));

        for scope in [Scope::Global, acme.clone(), other.clone()] {
            let roles = source.roles_for(&alice, &scope).await.expect("roles");
            let extra = source
                .extra_permissions(&alice, &scope)
                .await
                .expect("permissions");

            // A global grant reaches every scope, on both halves.
            assert!(roles.has(Role::Viewer), "{scope:?}");
            assert!(extra.has(Perm::AdminAccess), "{scope:?}");

            // A scoped grant reaches its own scope, on both halves.
            assert_eq!(
                roles.has(Role::Admin),
                extra.has(Perm::AdminSettings),
                "the two halves disagree about {scope:?}",
            );
            assert_eq!(roles.has(Role::Admin), scope == acme, "{scope:?}");
        }
    }

    /// The specific case the key-string form got wrong: a scope whose *key*
    /// happens to read as another one's is still a different scope.
    #[tokio::test]
    async fn a_direct_grant_does_not_leak_into_a_scope_that_only_looks_alike() {
        let alice = ActorId::new("usr_1");
        let team = Scope::Custom {
            kind: "org".to_owned(),
            id: ScopeId::new("acme"),
        };

        let source = MemoryRoleSource::<Role>::new();
        source.grant_permissions(alice.clone(), &team, PermSet::of([Perm::AdminSettings]));

        // `Scope::Org(acme)` and `Scope::Custom { kind: "org", id: acme }`
        // render the same key and are not the same scope. `covers` compares the
        // values; a key comparison could not tell them apart.
        assert_eq!(team.as_key(), Scope::Org(ScopeId::new("acme")).as_key());
        assert!(
            source
                .extra_permissions(&alice, &Scope::Org(ScopeId::new("acme")))
                .await
                .expect("permissions")
                .is_empty(),
        );
        assert!(
            !source
                .extra_permissions(&alice, &team)
                .await
                .expect("permissions")
                .is_empty(),
        );
    }

    #[tokio::test]
    async fn a_default_role_source_grants_nothing_extra() {
        struct Empty;

        impl RoleSource<Role> for Empty {
            fn roles_for<'a>(
                &'a self,
                _subject: &'a ActorId,
                _scope: &'a Scope,
            ) -> BoxFuture<'a, crate::Result<RoleSet<Role>>> {
                Box::pin(async { Ok(RoleSet::empty()) })
            }
        }

        let source = Empty;
        assert!(
            source
                .extra_permissions(&ActorId::new("usr_1"), &Scope::Global)
                .await
                .expect("permissions")
                .is_empty()
        );
        assert!(
            source
                .assignments(&ActorId::new("usr_1"))
                .await
                .expect("assignments")
                .is_empty()
        );
    }
}
